import type { Product, WidthOption } from './types.js'

const ONE: WidthOption = { code: 'OS', label: 'One size' }

/**
 * Handbags listed between 1,000 and 25,000 PKR on Bag X new arrivals.
 * Each price is five times that listing, converted at 277.00 PKR per USD on 2026-09-27 and rounded to the nearest dollar.
 */
export const bagxHandbags: Product[] = [
  {
    id: "bagx-monaco-choco",
    slug: "bagx-monaco-choco",
    name: "Monaco Choco",
    category: 'handbags',
    variant: 'simple',
    tagline: "Hobo bag",
    description: "Monaco Choco is a chocolate hobo bag from Bag X. Material: Suede. Closure: Drawstring. Gold-tone hardware.",
    priceCents: 5400,
    isNew: true,
    colors: [
      {
        slug: "choco",
        name: "Choco",
        swatch: ["#5c4030"],
        images: ["bagx-monaco-choco-1","bagx-monaco-choco-2","bagx-monaco-choco-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Hobo bag","Suede","Drawstring"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-MC-STD-2" },
      { label: "Style", value: "Hobo bag" },
      { label: "Color", value: "Choco" },
      { label: "Material", value: "Suede" },
      { label: "Closure", value: "Drawstring" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Hobo bag" },
    ],
    materials: "Suede",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-monaco-black",
    slug: "bagx-monaco-black",
    name: "Monaco Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Hobo bag",
    description: "Monaco Black is a black hobo bag from Bag X. Material: Suede. Closure: Drawstring. Gold-tone hardware.",
    priceCents: 5400,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-monaco-black-1","bagx-monaco-black-2","bagx-monaco-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Hobo bag","Suede","Drawstring"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-MB-STD-169399660927003" },
      { label: "Style", value: "Hobo bag" },
      { label: "Color", value: "Black" },
      { label: "Material", value: "Suede" },
      { label: "Closure", value: "Drawstring" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Hobo bag" },
    ],
    materials: "Suede",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-leo-maroon",
    slug: "bagx-leo-maroon",
    name: "Leo Maroon",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Leo Maroon is a maroon shoulder bag from Bag X. Material: Leather. Closure: Flap. Carry: Shoulder strap. Gold-tone hardware.",
    priceCents: 4500,
    isNew: true,
    colors: [
      {
        slug: "maroon",
        name: "Maroon",
        swatch: ["#6e2e33"],
        images: ["bagx-leo-maroon-1","bagx-leo-maroon-2","bagx-leo-maroon-3"],
        family: "red",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","Leather","Shoulder strap"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-LM-STD-1" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Maroon" },
      { label: "Material", value: "Leather" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Shoulder strap" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-nyra-beige",
    slug: "bagx-nyra-beige",
    name: "Nyra Beige",
    category: 'handbags',
    variant: 'simple',
    tagline: "Crossbody bag",
    description: "Nyra Beige is a beige crossbody bag from Bag X. Material: Leather.",
    priceCents: 7200,
    compareAtPriceCents: 10800,
    isNew: true,
    colors: [
      {
        slug: "beige",
        name: "Beige",
        swatch: ["#d8cbb8"],
        images: ["bagx-nyra-beige-1","bagx-nyra-beige-2","bagx-nyra-beige-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Crossbody bag","Leather"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-NB-STD-7" },
      { label: "Style", value: "Crossbody bag" },
      { label: "Color", value: "Beige" },
      { label: "Material", value: "Leather" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Crossbody bag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-nyra-pink",
    slug: "bagx-nyra-pink",
    name: "Nyra Pink",
    category: 'handbags',
    variant: 'simple',
    tagline: "Crossbody bag",
    description: "Nyra Pink is a pink crossbody bag from Bag X. Material: Leather.",
    priceCents: 7200,
    compareAtPriceCents: 10800,
    isNew: true,
    colors: [
      {
        slug: "pink",
        name: "Pink",
        swatch: ["#c9899a"],
        images: ["bagx-nyra-pink-1","bagx-nyra-pink-2","bagx-nyra-pink-3"],
        family: "red",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Crossbody bag","Leather"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-NYRA-STD-0" },
      { label: "Style", value: "Crossbody bag" },
      { label: "Color", value: "Pink" },
      { label: "Material", value: "Leather" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Crossbody bag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-opaline-silver",
    slug: "bagx-opaline-silver",
    name: "Opaline Silver",
    category: 'handbags',
    variant: 'simple',
    tagline: "Crossbody bag",
    description: "Opaline Silver is a silver crossbody bag from Bag X. Closure: Drawstring. Silver-tone hardware.",
    priceCents: 5400,
    compareAtPriceCents: 8200,
    isNew: true,
    colors: [
      {
        slug: "silver",
        name: "Silver",
        swatch: ["#c5c7c9"],
        images: ["bagx-opaline-silver-1","bagx-opaline-silver-2","bagx-opaline-silver-3"],
        family: "grey",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Crossbody bag","Drawstring"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-OS-STD-1" },
      { label: "Style", value: "Crossbody bag" },
      { label: "Color", value: "Silver" },
      { label: "Closure", value: "Drawstring" },
      { label: "Hardware", value: "Silver-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Crossbody bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-opaline-black",
    slug: "bagx-opaline-black",
    name: "Opaline Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Crossbody bag",
    description: "Opaline Black is a black crossbody bag from Bag X. Closure: Drawstring. Silver-tone hardware.",
    priceCents: 5400,
    compareAtPriceCents: 8200,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-opaline-black-1","bagx-opaline-black-2","bagx-opaline-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Crossbody bag","Drawstring"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-OB-STD-2" },
      { label: "Style", value: "Crossbody bag" },
      { label: "Color", value: "Black" },
      { label: "Closure", value: "Drawstring" },
      { label: "Hardware", value: "Silver-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Crossbody bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-blue-palm",
    slug: "bagx-blue-palm",
    name: "Blue Palm",
    category: 'handbags',
    variant: 'simple',
    tagline: "Crossbody bag",
    description: "Blue Palm is a blue crossbody bag from Bag X. Material: Canvas. Closure: Zipper. Carry: Shoulder strap.",
    priceCents: 3400,
    compareAtPriceCents: 7200,
    isNew: true,
    colors: [
      {
        slug: "blue",
        name: "Blue",
        swatch: ["#1d4e89"],
        images: ["bagx-blue-palm-1","bagx-blue-palm-2","bagx-blue-palm-3"],
        family: "blue",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Crossbody bag","Canvas","Shoulder strap"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-BP-STD-0" },
      { label: "Style", value: "Crossbody bag" },
      { label: "Color", value: "Blue" },
      { label: "Material", value: "Canvas" },
      { label: "Closure", value: "Zipper" },
      { label: "Strap", value: "Shoulder strap" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Crossbody bag" },
    ],
    materials: "Canvas",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-xyra-choco",
    slug: "bagx-xyra-choco",
    name: "Xyra Choco",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Xyra Choco is a chocolate shoulder bag from Bag X. Material: Suede. Closure: Flap. Carry: Shoulder strap. Gold-tone hardware.",
    priceCents: 4700,
    compareAtPriceCents: 6900,
    isNew: true,
    colors: [
      {
        slug: "choco",
        name: "Choco",
        swatch: ["#5c4030"],
        images: ["bagx-xyra-choco-1","bagx-xyra-choco-2","bagx-xyra-choco-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","Suede","Shoulder strap"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-ZC-STD-0" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Choco" },
      { label: "Material", value: "Suede" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Shoulder strap" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Suede",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-xyra-black",
    slug: "bagx-xyra-black",
    name: "Xyra Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Xyra Black is a black shoulder bag from Bag X. Material: Suede. Closure: Flap. Carry: Shoulder strap. Gold-tone hardware.",
    priceCents: 4700,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-xyra-black-1","bagx-xyra-black-2","bagx-xyra-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","Suede","Shoulder strap"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-ZB-STD-0" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Black" },
      { label: "Material", value: "Suede" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Shoulder strap" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Suede",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-mulan-black",
    slug: "bagx-mulan-black",
    name: "Mulan Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Handbag",
    description: "Mulan Black is a black handbag from Bag X. Material: Leather. Closure: Flap. Carry: Top handle. Gold-tone hardware.",
    priceCents: 4500,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-mulan-black-1","bagx-mulan-black-2","bagx-mulan-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Handbag","Leather","Top handle"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-MB-STD-169399660927005" },
      { label: "Style", value: "Handbag" },
      { label: "Color", value: "Black" },
      { label: "Material", value: "Leather" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Top handle" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Handbag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-mulan-choco",
    slug: "bagx-mulan-choco",
    name: "Mulan Choco",
    category: 'handbags',
    variant: 'simple',
    tagline: "Handbag",
    description: "Mulan Choco is a chocolate handbag from Bag X. Material: Leather. Closure: Flap. Carry: Top handle. Gold-tone hardware.",
    priceCents: 4500,
    isNew: true,
    colors: [
      {
        slug: "choco",
        name: "Choco",
        swatch: ["#5c4030"],
        images: ["bagx-mulan-choco-1","bagx-mulan-choco-2","bagx-mulan-choco-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Handbag","Leather","Top handle"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-MC-STD-3" },
      { label: "Style", value: "Handbag" },
      { label: "Color", value: "Choco" },
      { label: "Material", value: "Leather" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Top handle" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Handbag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-evline-beige-brown",
    slug: "bagx-evline-beige-brown",
    name: "Evline Beige/Brown",
    category: 'handbags',
    variant: 'simple',
    tagline: "Three-piece set",
    description: "Evline Beige/Brown is a beige and brown three-piece set from Bag X. The set includes a tote, crossbody, and pouch. Material: Suede. Closure: Zipper. Carry: Adjustable strap, Top handle. Gold-tone hardware.",
    priceCents: 4700,
    isNew: true,
    colors: [
      {
        slug: "beige-brown",
        name: "Beige / Brown",
        swatch: ["#d8cbb8","#6b4a32"],
        images: ["bagx-evline-beige-brown-1","bagx-evline-beige-brown-2","bagx-evline-beige-brown-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Three-piece set","Suede","Adjustable strap, Top handle"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-EVLINE-03" },
      { label: "Style", value: "Three-piece set" },
      { label: "Color", value: "Beige / Brown" },
      { label: "Material", value: "Suede" },
      { label: "Closure", value: "Zipper" },
      { label: "Strap", value: "Adjustable strap, Top handle" },
      { label: "Hardware", value: "Gold-tone hardware" },
      { label: "Set includes", value: "tote, crossbody, and pouch" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Three-piece set" },
    ],
    materials: "Suede",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "The strap is adjustable. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: [],
  },
  {
    id: "bagx-evline-brown-black",
    slug: "bagx-evline-brown-black",
    name: "Evline Brown/Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Three-piece set",
    description: "Evline Brown/Black is a brown and black three-piece set from Bag X. The set includes a tote, crossbody, and pouch. Material: Suede. Closure: Zipper. Carry: Adjustable strap, Top handle. Gold-tone hardware.",
    priceCents: 4700,
    isNew: true,
    colors: [
      {
        slug: "brown-black",
        name: "Brown / Black",
        swatch: ["#6b4a32","#161616"],
        images: ["bagx-evline-brown-black-1","bagx-evline-brown-black-2","bagx-evline-brown-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Three-piece set","Suede","Adjustable strap, Top handle"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-EVLINE-04" },
      { label: "Style", value: "Three-piece set" },
      { label: "Color", value: "Brown / Black" },
      { label: "Material", value: "Suede" },
      { label: "Closure", value: "Zipper" },
      { label: "Strap", value: "Adjustable strap, Top handle" },
      { label: "Hardware", value: "Gold-tone hardware" },
      { label: "Set includes", value: "tote, crossbody, and pouch" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Three-piece set" },
    ],
    materials: "Suede",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "The strap is adjustable. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: [],
  },
  {
    id: "bagx-niro-white",
    slug: "bagx-niro-white",
    name: "Niro White",
    category: 'handbags',
    variant: 'simple',
    tagline: "Handbag",
    description: "Niro White is a white handbag from Bag X. Material: Leather. Closure: Flap. Carry: Top handle, Chain strap.",
    priceCents: 4500,
    isNew: true,
    colors: [
      {
        slug: "white",
        name: "White",
        swatch: ["#f4f1ea"],
        images: ["bagx-niro-white-1","bagx-niro-white-2","bagx-niro-white-3"],
        family: "white",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Handbag","Leather","Top handle, Chain strap"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-NW-STD-0" },
      { label: "Style", value: "Handbag" },
      { label: "Color", value: "White" },
      { label: "Material", value: "Leather" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Top handle, Chain strap" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Handbag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-jinx-choco",
    slug: "bagx-jinx-choco",
    name: "Jinx Choco",
    category: 'handbags',
    variant: 'simple',
    tagline: "Hobo bag",
    description: "Jinx Choco is a chocolate hobo bag from Bag X. Material: Leather. Closure: Zipper. Carry: Shoulder strap. Gold-tone hardware.",
    priceCents: 5100,
    isNew: true,
    colors: [
      {
        slug: "choco",
        name: "Choco",
        swatch: ["#5c4030"],
        images: ["bagx-jinx-choco-1","bagx-jinx-choco-2","bagx-jinx-choco-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Hobo bag","Leather","Shoulder strap"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-JB-STD-6" },
      { label: "Style", value: "Hobo bag" },
      { label: "Color", value: "Choco" },
      { label: "Material", value: "Leather" },
      { label: "Closure", value: "Zipper" },
      { label: "Strap", value: "Shoulder strap" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Hobo bag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-leo-brown",
    slug: "bagx-leo-brown",
    name: "Leo Brown",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Leo Brown is a brown shoulder bag from Bag X. Material: Leather. Closure: Flap. Carry: Shoulder strap. Gold-tone hardware.",
    priceCents: 4500,
    isNew: true,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6b4a32"],
        images: ["bagx-leo-brown-1","bagx-leo-brown-2","bagx-leo-brown-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","Leather","Shoulder strap"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-LB-STD-8" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Brown" },
      { label: "Material", value: "Leather" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Shoulder strap" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-jinx-black",
    slug: "bagx-jinx-black",
    name: "Jinx Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Hobo bag",
    description: "Jinx Black is a black hobo bag from Bag X. Material: Leather. Closure: Zipper. Carry: Shoulder strap. Gold-tone hardware.",
    priceCents: 5100,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-jinx-black-1","bagx-jinx-black-2","bagx-jinx-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Hobo bag","Leather","Shoulder strap"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-JB-STD-5" },
      { label: "Style", value: "Hobo bag" },
      { label: "Color", value: "Black" },
      { label: "Material", value: "Leather" },
      { label: "Closure", value: "Zipper" },
      { label: "Strap", value: "Shoulder strap" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Hobo bag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-geneva-black",
    slug: "bagx-geneva-black",
    name: "Geneva Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Geneva Black is a black shoulder bag from Bag X. Dimensions: 10 in wide, 6 in long, and 3 in deep. Closure: Flap with twist-lock. Gold-tone hardware.",
    priceCents: 3100,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-geneva-black-1","bagx-geneva-black-2","bagx-geneva-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","10 in wide, 6 in long, and 3 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-GB-STD-4" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Black" },
      { label: "Dimensions", value: "10 in wide, 6 in long, and 3 in deep" },
      { label: "Closure", value: "Flap with twist-lock" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-celine-black",
    slug: "bagx-celine-black",
    name: "Celine Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Handbag",
    description: "Celine Black is a black handbag from Bag X. Material: Leather. Closure: Flap. Carry: Top handle. Silver-tone hardware.",
    priceCents: 7200,
    compareAtPriceCents: 10800,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-celine-black-1","bagx-celine-black-2","bagx-celine-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Handbag","Leather","Top handle"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-CB-STD-8" },
      { label: "Style", value: "Handbag" },
      { label: "Color", value: "Black" },
      { label: "Material", value: "Leather" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Top handle" },
      { label: "Hardware", value: "Silver-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Handbag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-aries-black",
    slug: "bagx-aries-black",
    name: "Aries Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Crossbody bag",
    description: "Aries Black is a black crossbody bag from Bag X. Dimensions: 9 in wide, 5 in high, and 2.5 in deep. Closure: Flap. Carry: Shoulder strap.",
    priceCents: 3400,
    compareAtPriceCents: 6300,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-aries-black-1","bagx-aries-black-2","bagx-aries-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Crossbody bag","9 in wide, 5 in high, and 2.5 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-AB-STD-3" },
      { label: "Style", value: "Crossbody bag" },
      { label: "Color", value: "Black" },
      { label: "Dimensions", value: "9 in wide, 5 in high, and 2.5 in deep" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Shoulder strap" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Crossbody bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-mars-black",
    slug: "bagx-mars-black",
    name: "Mars Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Handbag",
    description: "Mars Black is a black handbag from Bag X. Dimensions: 14 in wide, 7 in high, and 4 in deep.",
    priceCents: 5100,
    compareAtPriceCents: 8100,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-mars-black-1","bagx-mars-black-2","bagx-mars-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Handbag","14 in wide, 7 in high, and 4 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-MB-STD-169399660927002" },
      { label: "Style", value: "Handbag" },
      { label: "Color", value: "Black" },
      { label: "Dimensions", value: "14 in wide, 7 in high, and 4 in deep" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Handbag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-aries-maroon",
    slug: "bagx-aries-maroon",
    name: "Aries Maroon",
    category: 'handbags',
    variant: 'simple',
    tagline: "Crossbody bag",
    description: "Aries Maroon is a maroon crossbody bag from Bag X. Dimensions: 9 in wide, 5 in high, and 2.5 in deep. Closure: Flap. Carry: Shoulder strap.",
    priceCents: 3400,
    compareAtPriceCents: 6300,
    isNew: true,
    colors: [
      {
        slug: "maroon",
        name: "Maroon",
        swatch: ["#6e2e33"],
        images: ["bagx-aries-maroon-1","bagx-aries-maroon-2","bagx-aries-maroon-3"],
        family: "red",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Crossbody bag","9 in wide, 5 in high, and 2.5 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-AM-STD-3" },
      { label: "Style", value: "Crossbody bag" },
      { label: "Color", value: "Maroon" },
      { label: "Dimensions", value: "9 in wide, 5 in high, and 2.5 in deep" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Shoulder strap" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Crossbody bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-mars-choco",
    slug: "bagx-mars-choco",
    name: "Mars Choco",
    category: 'handbags',
    variant: 'simple',
    tagline: "Handbag",
    description: "Mars Choco is a chocolate handbag from Bag X. Dimensions: 14 in wide, 7 in high, and 4 in deep.",
    priceCents: 5100,
    compareAtPriceCents: 8100,
    isNew: true,
    colors: [
      {
        slug: "choco",
        name: "Choco",
        swatch: ["#5c4030"],
        images: ["bagx-mars-choco-1","bagx-mars-choco-2","bagx-mars-choco-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Handbag","14 in wide, 7 in high, and 4 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-MC-STD-1" },
      { label: "Style", value: "Handbag" },
      { label: "Color", value: "Choco" },
      { label: "Dimensions", value: "14 in wide, 7 in high, and 4 in deep" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Handbag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-ayla-black",
    slug: "bagx-ayla-black",
    name: "Ayla Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Handbag",
    description: "Ayla Black is a black handbag from Bag X. Dimensions: 12 in wide, 6 in high, and 3 in deep. Closure: Flap. Carry: Top handle. Gold-tone hardware.",
    priceCents: 5100,
    compareAtPriceCents: 6300,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-ayla-black-1","bagx-ayla-black-2","bagx-ayla-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Handbag","12 in wide, 6 in high, and 3 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-AB-STD-2" },
      { label: "Style", value: "Handbag" },
      { label: "Color", value: "Black" },
      { label: "Dimensions", value: "12 in wide, 6 in high, and 3 in deep" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Top handle" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Handbag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-veya-black",
    slug: "bagx-veya-black",
    name: "Veya Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Hobo bag",
    description: "Veya Black is a black hobo bag from Bag X. Material: Leather. Closure: Zipper. Carry: Top handle.",
    priceCents: 5200,
    compareAtPriceCents: 7200,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-veya-black-1","bagx-veya-black-2","bagx-veya-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Hobo bag","Leather","Top handle"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-VB-STD-4" },
      { label: "Style", value: "Hobo bag" },
      { label: "Color", value: "Black" },
      { label: "Material", value: "Leather" },
      { label: "Closure", value: "Zipper" },
      { label: "Strap", value: "Top handle" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Hobo bag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-ayla-choco",
    slug: "bagx-ayla-choco",
    name: "Ayla Choco",
    category: 'handbags',
    variant: 'simple',
    tagline: "Handbag",
    description: "Ayla Choco is a chocolate handbag from Bag X. Dimensions: 12 in wide, 6 in high, and 3 in deep. Closure: Flap. Carry: Top handle. Gold-tone hardware.",
    priceCents: 5100,
    compareAtPriceCents: 6300,
    isNew: true,
    colors: [
      {
        slug: "choco",
        name: "Choco",
        swatch: ["#5c4030"],
        images: ["bagx-ayla-choco-1","bagx-ayla-choco-2","bagx-ayla-choco-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Handbag","12 in wide, 6 in high, and 3 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-AC-STD-2" },
      { label: "Style", value: "Handbag" },
      { label: "Color", value: "Choco" },
      { label: "Dimensions", value: "12 in wide, 6 in high, and 3 in deep" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Top handle" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Handbag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-nice-black",
    slug: "bagx-nice-black",
    name: "Nice Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Crossbody bag",
    description: "Nice Black is a black crossbody bag from Bag X. Material: Faux leather. Closure: Flap. Carry: Chain strap. Gold-tone hardware.",
    priceCents: 4100,
    compareAtPriceCents: 6300,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-nice-black-1","bagx-nice-black-2","bagx-nice-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Crossbody bag","Faux leather","Chain strap"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-NB-STD-2" },
      { label: "Style", value: "Crossbody bag" },
      { label: "Color", value: "Black" },
      { label: "Material", value: "Faux leather" },
      { label: "Closure", value: "Flap" },
      { label: "Strap", value: "Chain strap" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Crossbody bag" },
    ],
    materials: "Faux leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-eli-brown",
    slug: "bagx-eli-brown",
    name: "Eli Brown",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Eli Brown is a brown shoulder bag from Bag X. Material: Faux leather. Dimensions: 10.5 in wide, 8 in high, and 3 in deep. Carry: Shoulder strap.",
    priceCents: 3400,
    compareAtPriceCents: 6300,
    isNew: true,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6b4a32"],
        images: ["bagx-eli-brown-1","bagx-eli-brown-2","bagx-eli-brown-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","Faux leather","10.5 in wide, 8 in high, and 3 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-EB-STD-2" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Brown" },
      { label: "Material", value: "Faux leather" },
      { label: "Dimensions", value: "10.5 in wide, 8 in high, and 3 in deep" },
      { label: "Strap", value: "Shoulder strap" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Faux leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-lapin-brown",
    slug: "bagx-lapin-brown",
    name: "Lapin Brown",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Lapin Brown is a brown shoulder bag from Bag X. Dimensions: 7 in wide, 10 in long, and 5 in deep.",
    priceCents: 5800,
    compareAtPriceCents: 8100,
    isNew: true,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6b4a32"],
        images: ["bagx-lapin-brown-1","bagx-lapin-brown-2","bagx-lapin-brown-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","7 in wide, 10 in long, and 5 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-LUPIN-STD-0" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Brown" },
      { label: "Dimensions", value: "7 in wide, 10 in long, and 5 in deep" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-kyoto-dusty-pink",
    slug: "bagx-kyoto-dusty-pink",
    name: "Kyoto Dusty Pink",
    category: 'handbags',
    variant: 'simple',
    tagline: "Crossbody bag",
    description: "Kyoto Dusty Pink is a dusty pink crossbody bag from Bag X. Pattern: Quilted. Carry: Adjustable strap, Top handle.",
    priceCents: 7200,
    compareAtPriceCents: 10800,
    isNew: true,
    colors: [
      {
        slug: "dusty-pink",
        name: "Dusty Pink",
        swatch: ["#c9899a"],
        images: ["bagx-kyoto-dusty-pink-1","bagx-kyoto-dusty-pink-2","bagx-kyoto-dusty-pink-3"],
        family: "red",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Crossbody bag","Quilted","Adjustable strap, Top handle"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-KDP-STD-0" },
      { label: "Style", value: "Crossbody bag" },
      { label: "Color", value: "Dusty Pink" },
      { label: "Pattern", value: "Quilted" },
      { label: "Strap", value: "Adjustable strap, Top handle" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Crossbody bag" },
    ],
    materials: "Quilted",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "The strap is adjustable. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-april-choco",
    slug: "bagx-april-choco",
    name: "April Choco",
    category: 'handbags',
    variant: 'simple',
    tagline: "Crossbody bag",
    description: "April Choco is a chocolate crossbody bag from Bag X. Material: Leather. Carry: Shoulder strap.",
    priceCents: 3200,
    compareAtPriceCents: 7200,
    isNew: true,
    colors: [
      {
        slug: "choco",
        name: "Choco",
        swatch: ["#5c4030"],
        images: ["bagx-april-choco-1","bagx-april-choco-2","bagx-april-choco-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Crossbody bag","Leather","Shoulder strap"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-AC-STD-1" },
      { label: "Style", value: "Crossbody bag" },
      { label: "Color", value: "Choco" },
      { label: "Material", value: "Leather" },
      { label: "Strap", value: "Shoulder strap" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Crossbody bag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-april-brown",
    slug: "bagx-april-brown",
    name: "April Brown",
    category: 'handbags',
    variant: 'simple',
    tagline: "Crossbody bag",
    description: "April Brown is a brown crossbody bag from Bag X. Material: Leather. Carry: Shoulder strap.",
    priceCents: 3200,
    compareAtPriceCents: 7200,
    isNew: true,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6b4a32"],
        images: ["bagx-april-brown-1","bagx-april-brown-2","bagx-april-brown-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Crossbody bag","Leather","Shoulder strap"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-AB-STD-1" },
      { label: "Style", value: "Crossbody bag" },
      { label: "Color", value: "Brown" },
      { label: "Material", value: "Leather" },
      { label: "Strap", value: "Shoulder strap" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Crossbody bag" },
    ],
    materials: "Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-cairo-beige",
    slug: "bagx-cairo-beige",
    name: "Cairo Beige",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Cairo Beige is a beige shoulder bag from Bag X. Dimensions: 11 in wide, 6 in long, and 3 in deep. Gold-tone hardware.",
    priceCents: 3200,
    compareAtPriceCents: 5100,
    isNew: true,
    colors: [
      {
        slug: "beige",
        name: "Beige",
        swatch: ["#d8cbb8"],
        images: ["bagx-cairo-beige-1","bagx-cairo-beige-2","bagx-cairo-beige-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","11 in wide, 6 in long, and 3 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-CB-STD-5" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Beige" },
      { label: "Dimensions", value: "11 in wide, 6 in long, and 3 in deep" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-geneva-brown",
    slug: "bagx-geneva-brown",
    name: "Geneva Brown",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Geneva Brown is a brown shoulder bag from Bag X. Dimensions: 10 in wide, 6 in long, and 3 in deep. Closure: Flap with twist-lock. Gold-tone hardware.",
    priceCents: 3100,
    isNew: true,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6b4a32"],
        images: ["bagx-geneva-brown-1","bagx-geneva-brown-2","bagx-geneva-brown-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","10 in wide, 6 in long, and 3 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-GB-STD-2" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Brown" },
      { label: "Dimensions", value: "10 in wide, 6 in long, and 3 in deep" },
      { label: "Closure", value: "Flap with twist-lock" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-derby-maroon",
    slug: "bagx-derby-maroon",
    name: "Derby Maroon",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Derby Maroon is a maroon shoulder bag from Bag X. Dimensions: 10 in wide, 5.5 in long, and 2.5 in deep.",
    priceCents: 3200,
    compareAtPriceCents: 7200,
    isNew: true,
    colors: [
      {
        slug: "maroon",
        name: "Maroon",
        swatch: ["#6e2e33"],
        images: ["bagx-derby-maroon-1","bagx-derby-maroon-2","bagx-derby-maroon-3"],
        family: "red",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","10 in wide, 5.5 in long, and 2.5 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-DM-STD-0" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Maroon" },
      { label: "Dimensions", value: "10 in wide, 5.5 in long, and 2.5 in deep" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-derby-brown",
    slug: "bagx-derby-brown",
    name: "Derby Brown",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Derby Brown is a brown shoulder bag from Bag X. Dimensions: 10 in wide, 5.5 in long, and 2.5 in deep.",
    priceCents: 3200,
    isNew: true,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6b4a32"],
        images: ["bagx-derby-brown-1","bagx-derby-brown-2","bagx-derby-brown-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","10 in wide, 5.5 in long, and 2.5 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-DB-STD-169400594978452" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Brown" },
      { label: "Dimensions", value: "10 in wide, 5.5 in long, and 2.5 in deep" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-paris-choco",
    slug: "bagx-paris-choco",
    name: "Paris Choco",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Paris Choco is a chocolate shoulder bag from Bag X. Dimensions: 12 in wide, 8 in long, and 2.5 in deep.",
    priceCents: 3600,
    compareAtPriceCents: 7200,
    isNew: true,
    colors: [
      {
        slug: "choco",
        name: "Choco",
        swatch: ["#5c4030"],
        images: ["bagx-paris-choco-1","bagx-paris-choco-2","bagx-paris-choco-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","12 in wide, 8 in long, and 2.5 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-PC-STD-0" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Choco" },
      { label: "Dimensions", value: "12 in wide, 8 in long, and 2.5 in deep" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-paris-black",
    slug: "bagx-paris-black",
    name: "Paris Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Paris Black is a black shoulder bag from Bag X. Dimensions: 12 in wide, 8 in long, and 2.5 in deep.",
    priceCents: 3600,
    compareAtPriceCents: 7200,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-paris-black-1","bagx-paris-black-2","bagx-paris-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","12 in wide, 8 in long, and 2.5 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-PB-STD-0" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Black" },
      { label: "Dimensions", value: "12 in wide, 8 in long, and 2.5 in deep" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-barcelona-maroon",
    slug: "bagx-barcelona-maroon",
    name: "Barcelona Maroon",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Barcelona Maroon is a maroon shoulder bag from Bag X. Material: Premium Faux Leather. Dimensions: 9.5 in wide, 6.5 in long, and 2.5 in deep. Compartments: 1 Large Main Compartment.",
    priceCents: 3400,
    isNew: true,
    colors: [
      {
        slug: "maroon",
        name: "Maroon",
        swatch: ["#6e2e33"],
        images: ["bagx-barcelona-maroon-1","bagx-barcelona-maroon-2","bagx-barcelona-maroon-3"],
        family: "red",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","Premium Faux Leather","9.5 in wide, 6.5 in long, and 2.5 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-BM-STD-2" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Maroon" },
      { label: "Material", value: "Premium Faux Leather" },
      { label: "Dimensions", value: "9.5 in wide, 6.5 in long, and 2.5 in deep" },
      { label: "Compartments", value: "1 Large Main Compartment" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Premium Faux Leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-selena-black",
    slug: "bagx-selena-black",
    name: "Selena Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Selena Black is a black shoulder bag from Bag X. Material: Suede.",
    priceCents: 5800,
    compareAtPriceCents: 7500,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-selena-black-1","bagx-selena-black-2","bagx-selena-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","Suede"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-SELEN-STD-0" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Black" },
      { label: "Material", value: "Suede" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Suede",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-lorene-black",
    slug: "bagx-lorene-black",
    name: "Lorene Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Lorene Black is a black shoulder bag from Bag X. Dimensions: 12 in wide, 11 in long, and 5 in deep.",
    priceCents: 5400,
    compareAtPriceCents: 7000,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-lorene-black-1","bagx-lorene-black-2","bagx-lorene-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","12 in wide, 11 in long, and 5 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "00946-1P-03" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Black" },
      { label: "Dimensions", value: "12 in wide, 11 in long, and 5 in deep" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-lorene-beige",
    slug: "bagx-lorene-beige",
    name: "Lorene Beige",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Lorene Beige is a beige shoulder bag from Bag X. Dimensions: 12 in wide, 11 in long, and 5 in deep.",
    priceCents: 5400,
    compareAtPriceCents: 7000,
    isNew: true,
    colors: [
      {
        slug: "beige",
        name: "Beige",
        swatch: ["#d8cbb8"],
        images: ["bagx-lorene-beige-1","bagx-lorene-beige-2","bagx-lorene-beige-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","12 in wide, 11 in long, and 5 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "00946-1P-02" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Beige" },
      { label: "Dimensions", value: "12 in wide, 11 in long, and 5 in deep" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-kyoto-pink",
    slug: "bagx-kyoto-pink",
    name: "Kyoto Pink",
    category: 'handbags',
    variant: 'simple',
    tagline: "Crossbody bag",
    description: "Kyoto Pink is a pink crossbody bag from Bag X. Pattern: Quilted. Carry: Adjustable strap, Top handle.",
    priceCents: 7200,
    compareAtPriceCents: 10800,
    isNew: true,
    colors: [
      {
        slug: "pink",
        name: "Pink",
        swatch: ["#c9899a"],
        images: ["bagx-kyoto-pink-1","bagx-kyoto-pink-2","bagx-kyoto-pink-3"],
        family: "red",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Crossbody bag","Quilted","Adjustable strap, Top handle"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-KP-STD-0" },
      { label: "Style", value: "Crossbody bag" },
      { label: "Color", value: "Pink" },
      { label: "Pattern", value: "Quilted" },
      { label: "Strap", value: "Adjustable strap, Top handle" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Crossbody bag" },
    ],
    materials: "Quilted",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "The strap is adjustable. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-cairo-black",
    slug: "bagx-cairo-black",
    name: "Cairo Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Cairo Black is a black shoulder bag from Bag X. Carry: Cream strap. Gold-tone hardware.",
    priceCents: 3200,
    compareAtPriceCents: 5100,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-cairo-black-1","bagx-cairo-black-2","bagx-cairo-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","Cream strap"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "BAG-CB-STD-7" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Black" },
      { label: "Strap", value: "Cream strap" },
      { label: "Hardware", value: "Gold-tone hardware" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Material is listed in the specifications when Bag X published it.",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-west-black",
    slug: "bagx-west-black",
    name: "West Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Handbag",
    description: "West Black is a black handbag from Bag X. Material: Premium quality faux leather. Dimensions: 11 in wide and 8 in long.",
    priceCents: 3600,
    compareAtPriceCents: 5500,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-west-black-1","bagx-west-black-2","bagx-west-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Handbag","Premium quality faux leather","11 in wide and 8 in long"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "00491-1P-03" },
      { label: "Style", value: "Handbag" },
      { label: "Color", value: "Black" },
      { label: "Material", value: "Premium quality faux leather" },
      { label: "Dimensions", value: "11 in wide and 8 in long" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Handbag" },
    ],
    materials: "Premium quality faux leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-mini-shein-beige",
    slug: "bagx-mini-shein-beige",
    name: "Mini Shein Beige",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Mini Shein Beige is a beige shoulder bag from Bag X. Material: Premium quality faux leather & Canvas. Dimensions: 9 in wide, 5.5 in long, and 2.75 in deep. Compartments: 1. It has 1 inside pocket.",
    priceCents: 3800,
    compareAtPriceCents: 4800,
    isNew: true,
    colors: [
      {
        slug: "beige",
        name: "Beige",
        swatch: ["#d8cbb8"],
        images: ["bagx-mini-shein-beige-1","bagx-mini-shein-beige-2","bagx-mini-shein-beige-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","Premium quality faux leather & Canvas","9 in wide, 5.5 in long, and 2.75 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "00490-1P-02" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Beige" },
      { label: "Material", value: "Premium quality faux leather & Canvas" },
      { label: "Dimensions", value: "9 in wide, 5.5 in long, and 2.75 in deep" },
      { label: "Compartments", value: "1" },
      { label: "Inside pocket", value: "1" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Premium quality faux leather & Canvas",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-mini-shein-maroon",
    slug: "bagx-mini-shein-maroon",
    name: "Mini Shein Maroon",
    category: 'handbags',
    variant: 'simple',
    tagline: "Shoulder bag",
    description: "Mini Shein Maroon is a maroon shoulder bag from Bag X. Material: Premium quality faux leather & Canvas. Dimensions: 9 in wide, 5.5 in long, and 2.75 in deep. Compartments: 1. It has 1 inside pocket.",
    priceCents: 3800,
    compareAtPriceCents: 4800,
    isNew: true,
    colors: [
      {
        slug: "maroon",
        name: "Maroon",
        swatch: ["#6e2e33"],
        images: ["bagx-mini-shein-maroon-1","bagx-mini-shein-maroon-2","bagx-mini-shein-maroon-3"],
        family: "red",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Shoulder bag","Premium quality faux leather & Canvas","9 in wide, 5.5 in long, and 2.75 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "00490-1P-14" },
      { label: "Style", value: "Shoulder bag" },
      { label: "Color", value: "Maroon" },
      { label: "Material", value: "Premium quality faux leather & Canvas" },
      { label: "Dimensions", value: "9 in wide, 5.5 in long, and 2.75 in deep" },
      { label: "Compartments", value: "1" },
      { label: "Inside pocket", value: "1" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Shoulder bag" },
    ],
    materials: "Premium quality faux leather & Canvas",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-ashford-beige",
    slug: "bagx-ashford-beige",
    name: "Ashford Beige",
    category: 'handbags',
    variant: 'simple',
    tagline: "Handbag",
    description: "Ashford Beige is a beige handbag from Bag X. Material: Premium quality faux leather. Dimensions: 11 in wide, 8.5 in long, and 3.5 in deep. Compartments: 1 Large Main Compartment, 1 small pocket inside.",
    priceCents: 4000,
    compareAtPriceCents: 5900,
    isNew: true,
    colors: [
      {
        slug: "beige",
        name: "Beige",
        swatch: ["#d8cbb8"],
        images: ["bagx-ashford-beige-1","bagx-ashford-beige-2","bagx-ashford-beige-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Handbag","Premium quality faux leather","11 in wide, 8.5 in long, and 3.5 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "00473-1P-02" },
      { label: "Style", value: "Handbag" },
      { label: "Color", value: "Beige" },
      { label: "Material", value: "Premium quality faux leather" },
      { label: "Dimensions", value: "11 in wide, 8.5 in long, and 3.5 in deep" },
      { label: "Compartments", value: "1 Large Main Compartment, 1 small pocket inside" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Handbag" },
    ],
    materials: "Premium quality faux leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "bagx-ashford-black",
    slug: "bagx-ashford-black",
    name: "Ashford Black",
    category: 'handbags',
    variant: 'simple',
    tagline: "Handbag",
    description: "Ashford Black is a black handbag from Bag X. Material: Premium quality faux leather. Dimensions: 11 in wide, 8.5 in long, and 3.5 in deep. Compartments: 1 Large Main Compartment, 1 small pocket inside.",
    priceCents: 4000,
    compareAtPriceCents: 5900,
    isNew: true,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["bagx-ashford-black-1","bagx-ashford-black-2","bagx-ashford-black-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: ["Handbag","Premium quality faux leather","11 in wide, 8.5 in long, and 3.5 in deep"],
    specs: [
      { label: "Brand", value: "Bag X" },
      { label: "SKU", value: "00473-1P-03" },
      { label: "Style", value: "Handbag" },
      { label: "Color", value: "Black" },
      { label: "Material", value: "Premium quality faux leather" },
      { label: "Dimensions", value: "11 in wide, 8.5 in long, and 3.5 in deep" },
      { label: "Compartments", value: "1 Large Main Compartment, 1 small pocket inside" },
    ],
    traits: [
      { group: 'Brand', value: 'Bag X' },
      { group: 'Style', value: "Handbag" },
    ],
    materials: "Premium quality faux leather",
    care: 'Wipe with a soft dry cloth. Keep suede and canvas dry, and do not machine wash.',
    fit: {
      summary: 'One size.',
      advice: "This bag is one size. No shoe size applies.",
    },
    bestFor: ["Everyday"],
    defaultStock: 8,
    stock: {
    },
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
]
