import type { Product, WidthOption } from './types.js'

const STANDARD: WidthOption = { code: 'D', label: 'Standard' }

/**
 * Men's sneakers and jogger-style shoes listed between 1,000 and 25,000 PKR on Ndure.
 * Each price is five times that listing, converted at 277.00 PKR per USD on 2026-09-27 and rounded to the nearest dollar.
 */
export const mensSneakers: Product[] = [
  {
    id: "ndure-kay-0003-black",
    slug: "ndure-kay-0003-black",
    name: "Men's Contrast Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Contrast Sneakers: black jogger-style lace-up sneakers from Ndure (style M-PR-KAY-0003). They have a mesh and synthetic upper on an EVA foam and thermoplastic rubber (TPR) sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 8800,
    compareAtPriceCents: 12600,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-kay-0003-black-1","ndure-kay-0003-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-up Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate/Thermoplastic Rubber"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-KAY-0003" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate/Thermoplastic Rubber" },
      { label: "Silhouette", value: "Lace-up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate/Thermoplastic Rubber",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-len-0013-grey",
    slug: "ndure-len-0013-grey",
    name: "Men's Retro Sneakers in Grey",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Retro Sneakers in Grey: jogger-style lace-up sneakers from Ndure (style M-PR-LEN-0013). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 7600,
    compareAtPriceCents: 10800,
    colors: [
      {
        slug: "grey",
        name: "Grey",
        swatch: ["#8d8a84"],
        images: ["ndure-len-0013-grey-1","ndure-len-0013-grey-2"],
        family: "grey",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LEN-0013" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-lok-0017-navy",
    slug: "ndure-lok-0017-navy",
    name: "Men's Mesh Sneakers in Navy",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Mesh Sneakers in Navy: jogger-style lace-up sneakers from Ndure (style M-PR-LOK-0017). They have a mesh upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 7600,
    compareAtPriceCents: 10800,
    colors: [
      {
        slug: "navy",
        name: "Navy",
        swatch: ["#1d4e89"],
        images: ["ndure-lok-0017-navy-1","ndure-lok-0017-navy-2"],
        family: "blue",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-up Sneakers","Mesh","EVA"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LOK-0017" },
      { label: "Upper Material", value: "Mesh" },
      { label: "Sole Material", value: "EVA" },
      { label: "Silhouette", value: "Lace-up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-up Sneakers" },
    ],
    materials: "Mesh. EVA",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-alr-0007-black",
    slug: "ndure-alr-0007-black",
    name: "Men's Heel Detail Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Heel Detail Sneakers: black jogger-style lace-up shoes from Ndure (style M-PR-ALR-0007). They have a mesh and synthetic upper on an EVA foam and thermoplastic rubber (TPR) sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 10100,
    compareAtPriceCents: 14400,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-alr-0007-black-1","ndure-alr-0007-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Shoes","Mesh with Synthetic","Ethylene Vinyl Acetate/Thermoplastic Rubber"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-ALR-0007" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate/Thermoplastic Rubber" },
      { label: "Fashion Silhouette", value: "Lace-Up Shoes" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Shoes" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate/Thermoplastic Rubber",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-len-0014-white",
    slug: "ndure-len-0014-white",
    name: "Men's Retro Sneakers in White",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Retro Sneakers in White: jogger-style lace-up sneakers from Ndure (style M-PR-LEN-0014). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 8800,
    compareAtPriceCents: 12600,
    colors: [
      {
        slug: "white",
        name: "White",
        swatch: ["#f4f1ea"],
        images: ["ndure-len-0014-white-1","ndure-len-0014-white-2"],
        family: "white",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LEN-0014" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-alr-0005-blk-wht",
    slug: "ndure-alr-0005-blk-wht",
    name: "Men's Lace-Up Sneakers in Black and White",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Lace-Up Sneakers in Black and White: jogger-style lace-up sneakers from Ndure (style M-PR-ALR-0005). They have an engineered knit upper on an EVA foam and thermoplastic rubber (TPR) sole. Available in US men's sizes 7–13, standard width only. Best for everyday training and all-day wear.",
    priceCents: 10700,
    compareAtPriceCents: 15300,
    colors: [
      {
        slug: "blk-wht",
        name: "Blk/Wht",
        swatch: ["#161616"],
        images: ["ndure-alr-0005-blk-wht-1","ndure-alr-0005-blk-wht-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12,13],
    widths: [STANDARD],
    highlights: ["Lace-up Sneakers","Engineered Knit","Ethylene Vinyl Acetate/Thermoplastic Rubber"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-ALR-0005" },
      { label: "Upper Material", value: "Engineered Knit" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate/Thermoplastic Rubber" },
      { label: "Fashion Silhouette", value: "Lace-up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-up Sneakers" },
    ],
    materials: "Engineered Knit. Ethylene Vinyl Acetate/Thermoplastic Rubber",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {
      "ndure-alr-0005-blk-wht:blk-wht:13:D": 0,
    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-trn-0011-black",
    slug: "ndure-trn-0011-black",
    name: "Men's Basic Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Basic Sneakers: black jogger-style lace-up sneakers from Ndure (style M-SN-TRN-0011). They have a mesh and synthetic upper on a polyurethane (PU) sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 6900,
    compareAtPriceCents: 9900,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-trn-0011-black-1","ndure-trn-0011-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-up Sneakers","Mesh with Synthetic","Polyurethane"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-TRN-0011" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Polyurethane" },
      { label: "Fashion Silhouette", value: "Lace-up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Polyurethane",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-leo-0026-navy",
    slug: "ndure-leo-0026-navy",
    name: "Men's Casual Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Casual Sneakers: navy jogger-style lace-up sneakers from Ndure (style M-PR-LEO-0026). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 5700,
    compareAtPriceCents: 8100,
    colors: [
      {
        slug: "navy",
        name: "Navy",
        swatch: ["#1d4e89"],
        images: ["ndure-leo-0026-navy-1","ndure-leo-0026-navy-2"],
        family: "blue",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-up Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LEO-0026" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Silhouette", value: "Lace-up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-trn-0015-navy",
    slug: "ndure-trn-0015-navy",
    name: "Men's Lace-Up Sneakers in Navy",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Lace-Up Sneakers in Navy: jogger-style lace-up sneakers from Ndure (style M-SN-TRN-0015). They have a mesh and synthetic upper on a polyurethane (PU) sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 7600,
    compareAtPriceCents: 10800,
    colors: [
      {
        slug: "navy",
        name: "Navy",
        swatch: ["#1d4e89"],
        images: ["ndure-trn-0015-navy-1","ndure-trn-0015-navy-2"],
        family: "blue",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneaker","Mesh with Synthetic","Polyurethane"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-TRN-0015" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Polyurethane" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneaker" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneaker" },
    ],
    materials: "Mesh with Synthetic. Polyurethane",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-lok-0015-beige",
    slug: "ndure-lok-0015-beige",
    name: "Men's Lace-Up Sneakers in Beige",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Lace-Up Sneakers in Beige: jogger-style lace-up sneakers from Ndure (style M-PR-LOK-0015). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 5900,
    compareAtPriceCents: 8500,
    colors: [
      {
        slug: "beige",
        name: "Beige",
        swatch: ["#d8cbb8"],
        images: ["ndure-lok-0015-beige-1","ndure-lok-0015-beige-2"],
        family: "neutral",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-up Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LOK-0015" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Silhouette", value: "Lace-up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-veg-0001-blk-blk",
    slug: "ndure-veg-0001-blk-blk",
    name: "Vega Active Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Vega Active Sneakers: black and black men's jogger-style lace-up sneakers from Ndure (style M-PR-VEG-0001). They have an engineered knit upper on an EVA foam and thermoplastic rubber (TPR) sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 12600,
    compareAtPriceCents: 18000,
    colors: [
      {
        slug: "blk-blk",
        name: "Blk/Blk",
        swatch: ["#161616"],
        images: ["ndure-veg-0001-blk-blk-1","ndure-veg-0001-blk-blk-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Engineered Knit","Ethylene Vinyl Acetate/Thermoplastic Rubber"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-VEG-0001" },
      { label: "Upper Material", value: "Engineered Knit" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate/Thermoplastic Rubber" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Engineered Knit. Ethylene Vinyl Acetate/Thermoplastic Rubber",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-eri-0001-black",
    slug: "ndure-eri-0001-black",
    name: "Men's Chunky Lace up Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Chunky Lace up Sneakers: black jogger-style lace-up sneakers from Ndure (style M-PR-ERI-0001). They have a mesh and synthetic upper on a man-made sole and thermoplastic sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 7600,
    compareAtPriceCents: 10800,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-eri-0001-black-1","ndure-eri-0001-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Mesh with Synthetic","Man-Made Sole/Thermoplastic"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-ERI-0001" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Man-Made Sole/Thermoplastic" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Man-Made Sole/Thermoplastic",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-alr-0008-off-white",
    slug: "ndure-alr-0008-off-white",
    name: "Men's NRG+ Active Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's NRG+ Active Sneakers: off white jogger-style lace-up sneakers from Ndure (style M-PR-ALR-0008). They have a mesh and synthetic upper on an EVA foam and thermoplastic rubber (TPR) sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 10100,
    compareAtPriceCents: 14400,
    colors: [
      {
        slug: "off-white",
        name: "Off White",
        swatch: ["#f4f1ea"],
        images: ["ndure-alr-0008-off-white-1","ndure-alr-0008-off-white-2"],
        family: "white",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate/Thermoplastic Rubber"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-ALR-0008" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate/Thermoplastic Rubber" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate/Thermoplastic Rubber",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-dor-0003-navy",
    slug: "ndure-dor-0003-navy",
    name: "Men's Panel-Detail Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Panel-Detail Sneakers: navy jogger-style lace-up sneakers from Ndure (style M-SN-DOR-0003). They have a mesh and synthetic upper on a man-made sole and thermoplastic sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 6300,
    compareAtPriceCents: 9000,
    colors: [
      {
        slug: "navy",
        name: "Navy",
        swatch: ["#1d4e89"],
        images: ["ndure-dor-0003-navy-1","ndure-dor-0003-navy-2"],
        family: "blue",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Mesh with Synthetic","Man-Made Sole/Thermoplastic"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-DOR-0003" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Man-Made Sole/Thermoplastic" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Man-Made Sole/Thermoplastic",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-alp-0004-black",
    slug: "ndure-alp-0004-black",
    name: "Men's Lace-Up Mesh Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Lace-Up Mesh Sneakers: black jogger-style lace-up sneakers from Ndure (style M-PR-ALP-0004). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 5700,
    compareAtPriceCents: 8100,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-alp-0004-black-1","ndure-alp-0004-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-ALP-0004" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-ult-0005-beige",
    slug: "ndure-ult-0005-beige",
    name: "Men's Mesh Mule Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Mesh Mule Sneakers: beige jogger-style sneakers from Ndure (style M-PR-ULT-0005). Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 6300,
    compareAtPriceCents: 9000,
    colors: [
      {
        slug: "beige",
        name: "Beige",
        swatch: ["#d8cbb8"],
        images: ["ndure-ult-0005-beige-1","ndure-ult-0005-beige-2"],
        family: "neutral",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Jogger"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-ULT-0005" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Jogger" },
    ],
    materials: "Materials listed in the specifications.",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {
      "ndure-ult-0005-beige:beige:12:D": 0,
    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-loc-0002-black",
    slug: "ndure-loc-0002-black",
    name: "Men's Lace-Up Sneakers in Black (LOC-0002)",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Lace-Up Sneakers in Black (LOC-0002): jogger-style lace-up sneakers from Ndure (style M-SC-LOC-0002). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–11, standard width only. Best for everyday training and all-day wear.",
    priceCents: 5700,
    compareAtPriceCents: 8100,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-loc-0002-black-1","ndure-loc-0002-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SC-LOC-0002" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-tyl-0020-grey",
    slug: "ndure-tyl-0020-grey",
    name: "Men's Monochrome Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Monochrome Sneakers: grey jogger-style lace-up sneakers from Ndure (style M-PR-TYL-0020). They have a mesh and synthetic upper on a man-made sole and thermoplastic sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 6300,
    compareAtPriceCents: 9000,
    colors: [
      {
        slug: "grey",
        name: "Grey",
        swatch: ["#8d8a84"],
        images: ["ndure-tyl-0020-grey-1","ndure-tyl-0020-grey-2"],
        family: "grey",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneaker","Mesh with Synthetic","Man-Made Sole/Thermoplastic"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-TYL-0020" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Man-Made Sole/Thermoplastic" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneaker" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneaker" },
    ],
    materials: "Mesh with Synthetic. Man-Made Sole/Thermoplastic",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {
      "ndure-tyl-0020-grey:grey:12:D": 0,
    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-vel-0038-khaki",
    slug: "ndure-vel-0038-khaki",
    name: "Men's Contrast Sole Sneakers in Khaki",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Contrast Sole Sneakers in Khaki: jogger-style lace-up sneakers from Ndure (style M-PR-VEL-0038). They have a mesh and synthetic upper on a polyurethane (PU) sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 6900,
    compareAtPriceCents: 9900,
    colors: [
      {
        slug: "khaki",
        name: "Khaki",
        swatch: ["#b7a27a"],
        images: ["ndure-vel-0038-khaki-1","ndure-vel-0038-khaki-2"],
        family: "neutral",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Mesh with Synthetic","Polyurethane"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-VEL-0038" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Polyurethane" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Polyurethane",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {
      "ndure-vel-0038-khaki:khaki:11:D": 0,
    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-kay-0004-white",
    slug: "ndure-kay-0004-white",
    name: "Men's Chunky Sole Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Chunky Sole Sneakers: white jogger-style lace-up sneakers from Ndure (style M-PR-KAY-0004). They have a mesh and synthetic upper on an EVA foam and thermoplastic rubber (TPR) sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 8800,
    compareAtPriceCents: 12600,
    colors: [
      {
        slug: "white",
        name: "White",
        swatch: ["#f4f1ea"],
        images: ["ndure-kay-0004-white-1","ndure-kay-0004-white-2"],
        family: "white",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate/Thermoplastic Rubber"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-KAY-0004" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate/Thermoplastic Rubber" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate/Thermoplastic Rubber",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {
      "ndure-kay-0004-white:white:10:D": 0,
      "ndure-kay-0004-white:white:12:D": 0,
    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-ult-0009-black",
    slug: "ndure-ult-0009-black",
    name: "Men's Lace-Up Sneakers in Black (ULT-0009)",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Lace-Up Sneakers in Black (ULT-0009): jogger-style lace-up sneakers from Ndure (style M-PR-ULT-0009). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 7600,
    compareAtPriceCents: 10800,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-ult-0009-black-1","ndure-ult-0009-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-ULT-0009" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {
      "ndure-ult-0009-black:black:10:D": 0,
      "ndure-ult-0009-black:black:12:D": 0,
    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-psc-0008-grey",
    slug: "ndure-psc-0008-grey",
    name: "Men's Lace-Up Sneakers in Grey",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Lace-Up Sneakers in Grey: jogger-style lace-up sneakers from Ndure (style M-PR-PSC-0008). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 6900,
    compareAtPriceCents: 9900,
    colors: [
      {
        slug: "grey",
        name: "Grey",
        swatch: ["#8d8a84"],
        images: ["ndure-psc-0008-grey-1","ndure-psc-0008-grey-2"],
        family: "grey",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-PSC-0008" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {
      "ndure-psc-0008-grey:grey:9:D": 0,
      "ndure-psc-0008-grey:grey:10:D": 0,
    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-mis-0008-grey",
    slug: "ndure-mis-0008-grey",
    name: "Men's Sculpted-Sole Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Sculpted-Sole Sneakers: grey jogger-style lace-up sneakers from Ndure (style M-PR-MIS-0008). They have an engineered knit upper on an EVA foam sole. Available in US men's sizes 8–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 8800,
    compareAtPriceCents: 12600,
    colors: [
      {
        slug: "grey",
        name: "Grey",
        swatch: ["#8d8a84"],
        images: ["ndure-mis-0008-grey-1","ndure-mis-0008-grey-2"],
        family: "grey",
      },
    ],
    sizes: [8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Engineered Knit","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-MIS-0008" },
      { label: "Upper Material", value: "Engineered Knit" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Engineered Knit. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {
      "ndure-mis-0008-grey:grey:9:D": 0,
    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-myk-0001-black",
    slug: "ndure-myk-0001-black",
    name: "Men's Color-Combination Sneakers",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Color-Combination Sneakers: black jogger-style lace-up sneakers from Ndure (style M-SN-MYK-0001). They have a mesh and synthetic upper on an EVA foam and thermoplastic sole. Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 9500,
    compareAtPriceCents: 13500,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-myk-0001-black-1","ndure-myk-0001-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-up Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate/ Thermoplastic"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-MYK-0001" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate/ Thermoplastic" },
      { label: "Fashion Silhouette", value: "Lace-up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-up Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate/ Thermoplastic",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {
      "ndure-myk-0001-black:black:9:D": 0,
      "ndure-myk-0001-black:black:10:D": 0,
      "ndure-myk-0001-black:black:11:D": 0,
      "ndure-myk-0001-black:black:12:D": 0,
    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-len-0006-black",
    slug: "ndure-len-0006-black",
    name: "Men's Mesh Sneakers in Black",
    category: 'shoes',
    shoeUse: "running",
    variant: 'footwear',
    tagline: "Jogger-style sneaker",
    description: "Men's Mesh Sneakers in Black: jogger-style sneakers from Ndure (style M-PR-LEN-0006). Available in US men's sizes 7–12, standard width only. Best for everyday training and all-day wear.",
    priceCents: 9500,
    compareAtPriceCents: 13500,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-len-0006-black-1","ndure-len-0006-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Jogger"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LEN-0006" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Jogger" },
    ],
    materials: "Materials listed in the specifications.",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday training","All-day wear"],
    defaultStock: 8,
    stock: {
      "ndure-len-0006-black:black:8:D": 0,
      "ndure-len-0006-black:black:9:D": 0,
      "ndure-len-0006-black:black:10:D": 0,
      "ndure-len-0006-black:black:12:D": 0,
    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-leo-0024-black",
    slug: "ndure-leo-0024-black",
    name: "Men's Black Slip-On Sneakers",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Black Slip-On Sneakers: slip-on sneakers from Ndure (style M-PR-LEO-0024). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 5100,
    compareAtPriceCents: 7200,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-leo-0024-black-1","ndure-leo-0024-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Slip-On Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LEO-0024" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Slip-On Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Slip-On Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-lok-0014-black",
    slug: "ndure-lok-0014-black",
    name: "Men's Everyday Sneakers in Black (LOK-0014)",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Everyday Sneakers in Black (LOK-0014): slip-on sneakers from Ndure (style M-PR-LOK-0014). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 6300,
    compareAtPriceCents: 9000,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-lok-0014-black-1","ndure-lok-0014-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Slip-on Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LOK-0014" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Silhouette", value: "Slip-on Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Slip-on Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-mis-0006-grey",
    slug: "ndure-mis-0006-grey",
    name: "Men's Slip-On Sneakers in Grey (MIS-0006)",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Slip-On Sneakers in Grey (MIS-0006): slip-on sneakers from Ndure (style M-PR-MIS-0006). They have an engineered knit upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 8200,
    compareAtPriceCents: 11700,
    colors: [
      {
        slug: "grey",
        name: "Grey",
        swatch: ["#8d8a84"],
        images: ["ndure-mis-0006-grey-1","ndure-mis-0006-grey-2"],
        family: "grey",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Slip-on Sneakers","Engineered Knit","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-MIS-0006" },
      { label: "Upper Material", value: "Engineered Knit" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Silhouette", value: "Slip-on Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Slip-on Sneakers" },
    ],
    materials: "Engineered Knit. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-len-0009-black",
    slug: "ndure-len-0009-black",
    name: "Men's Easy Fit Sneakers in Black",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Easy Fit Sneakers in Black: slip-on sneakers from Ndure (style M-PR-LEN-0009). They have an engineered knit upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 8200,
    compareAtPriceCents: 11700,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-len-0009-black-1","ndure-len-0009-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Slip-On Sneakers","Engineered Knit","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LEN-0009" },
      { label: "Upper Material", value: "Engineered Knit" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Silhouette", value: "Slip-On Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Slip-On Sneakers" },
    ],
    materials: "Engineered Knit. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-rig-0001-nvy-ofwht",
    slug: "ndure-rig-0001-nvy-ofwht",
    name: "Men's Contrast Sole Sneakers in Navy and Off-White",
    category: 'shoes',
    shoeUse: "lifestyle",
    variant: 'footwear',
    tagline: "Everyday sneaker",
    description: "Men's Contrast Sole Sneakers in Navy and Off-White: lace-up sneakers from Ndure (style M-SN-RIG-0001). They have a polyurethane upper on a thermoplastic rubber (TPR) sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 7600,
    compareAtPriceCents: 10800,
    colors: [
      {
        slug: "nvy-ofwht",
        name: "Nvy/Ofwht",
        swatch: ["#c4b8a8"],
        images: ["ndure-rig-0001-nvy-ofwht-1","ndure-rig-0001-nvy-ofwht-2"],
        family: "white",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneaker","Polyurethane","Thermoplastic Rubber"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-RIG-0001" },
      { label: "Upper Material", value: "Polyurethane" },
      { label: "Sole Material", value: "Thermoplastic Rubber" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneaker" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneaker" },
    ],
    materials: "Polyurethane. Thermoplastic Rubber",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-grn-0003-navy",
    slug: "ndure-grn-0003-navy",
    name: "Men's Easy Fit Sneakers in Navy",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Easy Fit Sneakers in Navy: slip-on sneakers from Ndure (style M-PR-GRN-0003). They have an engineered knit upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 7600,
    compareAtPriceCents: 10800,
    colors: [
      {
        slug: "navy",
        name: "Navy",
        swatch: ["#1d4e89"],
        images: ["ndure-grn-0003-navy-1","ndure-grn-0003-navy-2"],
        family: "blue",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Slip-On Sneakers","Engineered Knit","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-GRN-0003" },
      { label: "Upper Material", value: "Engineered Knit" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Slip-On Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Slip-On Sneakers" },
    ],
    materials: "Engineered Knit. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-ult-0007-beige",
    slug: "ndure-ult-0007-beige",
    name: "Men's Slip-On Sneakers in Beige",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Slip-On Sneakers in Beige: slip-on sneakers from Ndure (style M-PR-ULT-0007). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 6900,
    compareAtPriceCents: 9900,
    colors: [
      {
        slug: "beige",
        name: "Beige",
        swatch: ["#d8cbb8"],
        images: ["ndure-ult-0007-beige-1","ndure-ult-0007-beige-2"],
        family: "neutral",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Slip-On Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-ULT-0007" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Slip-On Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Slip-On Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-leo-0025-grey",
    slug: "ndure-leo-0025-grey",
    name: "Men's Slip-On Sneakers in Grey (LEO-0025)",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Slip-On Sneakers in Grey (LEO-0025): slip-on sneakers from Ndure (style M-PR-LEO-0025). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 5100,
    compareAtPriceCents: 7200,
    colors: [
      {
        slug: "grey",
        name: "Grey",
        swatch: ["#8d8a84"],
        images: ["ndure-leo-0025-grey-1","ndure-leo-0025-grey-2"],
        family: "grey",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Slip-On Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LEO-0025" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Slip-On Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Slip-On Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-nit-0008-tan",
    slug: "ndure-nit-0008-tan",
    name: "Men's Contrast Sole Shoes",
    category: 'shoes',
    shoeUse: "lifestyle",
    variant: 'footwear',
    tagline: "Everyday sneaker",
    description: "Men's Contrast Sole Shoes: tan smart casual shoes from Ndure (style M-SN-NIT-0008). They have a polyurethane upper on a thermoplastic rubber (TPR) sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 10100,
    compareAtPriceCents: 14400,
    colors: [
      {
        slug: "tan",
        name: "Tan",
        swatch: ["#c4a574"],
        images: ["ndure-nit-0008-tan-1","ndure-nit-0008-tan-2"],
        family: "neutral",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Smart Casual Shoes","Polyurethane","Thermoplastic Rubber"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-NIT-0008" },
      { label: "Upper Material", value: "Polyurethane" },
      { label: "Sole Material", value: "Thermoplastic Rubber" },
      { label: "Fashion Silhouette", value: "Smart Casual Shoes" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Smart Casual Shoes" },
    ],
    materials: "Polyurethane. Thermoplastic Rubber",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-lok-0019-black",
    slug: "ndure-lok-0019-black",
    name: "Men's Slip-On Sneakers in Black (LOK-0019)",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Slip-On Sneakers in Black (LOK-0019): slip-on sneakers from Ndure (style M-PR-LOK-0019). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 6900,
    compareAtPriceCents: 9900,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-lok-0019-black-1","ndure-lok-0019-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Slip-On Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LOK-0019" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Slip-On Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Slip-On Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-ron-0001-blk-olv",
    slug: "ndure-ron-0001-blk-olv",
    name: "Hasan Raheem Men's Tonal Black Sneaker",
    category: 'shoes',
    shoeUse: "lifestyle",
    variant: 'footwear',
    tagline: "Everyday sneaker",
    description: "Hasan Raheem Men's Tonal Black Sneaker: court sneakers from Ndure (style M-SN-RON-0001). They have a polyurethane upper on a thermoplastic rubber (TPR) sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 12600,
    colors: [
      {
        slug: "blk-olv",
        name: "Blk/Olv",
        swatch: ["#161616"],
        images: ["ndure-ron-0001-blk-olv-1","ndure-ron-0001-blk-olv-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Court Sneakers","Polyurethane","Thermoplastic Rubber"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-RON-0001" },
      { label: "Upper Material", value: "Polyurethane" },
      { label: "Sole Material", value: "Thermoplastic Rubber" },
      { label: "Fashion Silhouette", value: "Court Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Court Sneakers" },
    ],
    materials: "Polyurethane. Thermoplastic Rubber",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-ron-0002-blk-ofwht",
    slug: "ndure-ron-0002-blk-ofwht",
    name: "Hasan Raheem Men's Contrast Detail in Black and Off-White",
    category: 'shoes',
    shoeUse: "lifestyle",
    variant: 'footwear',
    tagline: "Everyday sneaker",
    description: "Hasan Raheem Men's Contrast Detail in Black and Off-White: court sneakers from Ndure (style M-SN-RON-0002). They have a polyurethane upper on a thermoplastic rubber (TPR) sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 12600,
    colors: [
      {
        slug: "blk-ofwht",
        name: "Blk/Ofwht",
        swatch: ["#161616"],
        images: ["ndure-ron-0002-blk-ofwht-1","ndure-ron-0002-blk-ofwht-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Court Sneakers","Polyurethane","Thermoplastic Rubber"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-RON-0002" },
      { label: "Upper Material", value: "Polyurethane" },
      { label: "Sole Material", value: "Thermoplastic Rubber" },
      { label: "Fashion Silhouette", value: "Court Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Court Sneakers" },
    ],
    materials: "Polyurethane. Thermoplastic Rubber",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-ron-0003-o-wht-beg",
    slug: "ndure-ron-0003-o-wht-beg",
    name: "Hasan Raheem Men's Contrast Detail in Off-White and Beige",
    category: 'shoes',
    shoeUse: "lifestyle",
    variant: 'footwear',
    tagline: "Everyday sneaker",
    description: "Hasan Raheem Men's Contrast Detail in Off-White and Beige: mid-top sneakers from Ndure (style M-SN-RON-0003). They have a polyurethane upper on a thermoplastic rubber (TPR) sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 12600,
    colors: [
      {
        slug: "o-wht-beg",
        name: "O.Wht/Beg",
        swatch: ["#c4b8a8"],
        images: ["ndure-ron-0003-o-wht-beg-1","ndure-ron-0003-o-wht-beg-2"],
        family: "white",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Mid-Top Sneakers","Polyurethane","Thermoplastic Rubber"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-RON-0003" },
      { label: "Upper Material", value: "Polyurethane" },
      { label: "Sole Material", value: "Thermoplastic Rubber" },
      { label: "Fashion Silhouette", value: "Mid-Top Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Mid-Top Sneakers" },
    ],
    materials: "Polyurethane. Thermoplastic Rubber",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-lok-0018-grey",
    slug: "ndure-lok-0018-grey",
    name: "Men's Mesh Sneakers in Grey",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Mesh Sneakers in Grey: slip-on sneakers from Ndure (style M-PR-LOK-0018). They have a mesh upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 5700,
    compareAtPriceCents: 8100,
    colors: [
      {
        slug: "grey",
        name: "Grey",
        swatch: ["#8d8a84"],
        images: ["ndure-lok-0018-grey-1","ndure-lok-0018-grey-2"],
        family: "grey",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Slip-on Sneakers","Mesh","EVA"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LOK-0018" },
      { label: "Upper Material", value: "Mesh" },
      { label: "Sole Material", value: "EVA" },
      { label: "Silhouette", value: "Slip-on Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Slip-on Sneakers" },
    ],
    materials: "Mesh. EVA",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-psc-0009-black",
    slug: "ndure-psc-0009-black",
    name: "Men's Everyday Sneakers in Black (PSC-0009)",
    category: 'shoes',
    shoeUse: "lifestyle",
    variant: 'footwear',
    tagline: "Everyday sneaker",
    description: "Men's Everyday Sneakers in Black (PSC-0009): sneakers from Ndure (style M-PR-PSC-0009). Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 8800,
    compareAtPriceCents: 12600,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-psc-0009-black-1","ndure-psc-0009-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Sneaker"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-PSC-0009" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Sneaker" },
    ],
    materials: "Materials listed in the specifications.",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-bra-0023-wht-blk",
    slug: "ndure-bra-0023-wht-blk",
    name: "Men's Contrast Panel Sneakers in White and Black",
    category: 'shoes',
    shoeUse: "lifestyle",
    variant: 'footwear',
    tagline: "Everyday sneaker",
    description: "Men's Contrast Panel Sneakers in White and Black: lace-up sneakers from Ndure (style M-SN-BRA-0023). They have a polyurethane upper on a man-made sole and thermoplastic sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 5100,
    compareAtPriceCents: 7200,
    colors: [
      {
        slug: "wht-blk",
        name: "Wht/Blk",
        swatch: ["#161616"],
        images: ["ndure-bra-0023-wht-blk-1","ndure-bra-0023-wht-blk-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Polyurethane","Man-Made Sole/Thermoplastic"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-BRA-0023" },
      { label: "Upper Material", value: "Polyurethane" },
      { label: "Sole Material", value: "Man-Made Sole/Thermoplastic" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Polyurethane. Man-Made Sole/Thermoplastic",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-nit-0010-sand",
    slug: "ndure-nit-0010-sand",
    name: "Men's Contrast Panel Sneakers in Sand",
    category: 'shoes',
    shoeUse: "lifestyle",
    variant: 'footwear',
    tagline: "Everyday sneaker",
    description: "Men's Contrast Panel Sneakers in Sand: lace-up sneakers from Ndure (style M-SN-NIT-0010). They have a polyurethane upper on a thermoplastic rubber (TPR) sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 10100,
    compareAtPriceCents: 14400,
    colors: [
      {
        slug: "sand",
        name: "Sand",
        swatch: ["#d7c4a3"],
        images: ["ndure-nit-0010-sand-1","ndure-nit-0010-sand-2"],
        family: "neutral",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Polyurethane","Thermoplastic Rubber"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-NIT-0010" },
      { label: "Upper Material", value: "Polyurethane" },
      { label: "Sole Material", value: "Thermoplastic Rubber" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Polyurethane. Thermoplastic Rubber",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-ori-0004-d-brown",
    slug: "ndure-ori-0004-d-brown",
    name: "Men's Thick Sole Sneakers",
    category: 'shoes',
    shoeUse: "lifestyle",
    variant: 'footwear',
    tagline: "Everyday sneaker",
    description: "Men's Thick Sole Sneakers: dark brown lace-up sneakers from Ndure (style M-PR-ORI-0004). They have a polyurethane upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 6900,
    compareAtPriceCents: 9900,
    colors: [
      {
        slug: "d-brown",
        name: "D.Brown",
        swatch: ["#6b4a32"],
        images: ["ndure-ori-0004-d-brown-1","ndure-ori-0004-d-brown-2"],
        family: "neutral",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-Up Sneakers","Polyurethane","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-ORI-0004" },
      { label: "Upper Material", value: "Polyurethane" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Lace-Up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-Up Sneakers" },
    ],
    materials: "Polyurethane. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-bra-0019-coffee",
    slug: "ndure-bra-0019-coffee",
    name: "Men's Smart Sneakers",
    category: 'shoes',
    shoeUse: "lifestyle",
    variant: 'footwear',
    tagline: "Everyday sneaker",
    description: "Men's Smart Sneakers: coffee low-top sneakers from Ndure (style M-SN-BRA-0019). They have a polyurethane upper on a man-made sole and thermoplastic sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 5700,
    compareAtPriceCents: 8100,
    colors: [
      {
        slug: "coffee",
        name: "Coffee",
        swatch: ["#c4b8a8"],
        images: ["ndure-bra-0019-coffee-1","ndure-bra-0019-coffee-2"],
        family: "neutral",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Low-top Sneakers","Polyurethane","Man-Made Sole/Thermoplastic"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-BRA-0019" },
      { label: "Upper Material", value: "Polyurethane" },
      { label: "Sole Material", value: "Man-Made Sole/Thermoplastic" },
      { label: "Silhouette", value: "Low-top Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Low-top Sneakers" },
    ],
    materials: "Polyurethane. Man-Made Sole/Thermoplastic",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-trn-0005-grey",
    slug: "ndure-trn-0005-grey",
    name: "Men's Contrast Sole Sneakers in Grey",
    category: 'shoes',
    shoeUse: "lifestyle",
    variant: 'footwear',
    tagline: "Everyday sneaker",
    description: "Men's Contrast Sole Sneakers in Grey: sneakers from Ndure (style M-SN-TRN-0005). Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 6300,
    compareAtPriceCents: 9000,
    colors: [
      {
        slug: "grey",
        name: "Grey",
        swatch: ["#8d8a84"],
        images: ["ndure-trn-0005-grey-1","ndure-trn-0005-grey-2"],
        family: "grey",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Sneaker"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-TRN-0005" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Sneaker" },
    ],
    materials: "Materials listed in the specifications.",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-leo-0028-navy",
    slug: "ndure-leo-0028-navy",
    name: "Men's Laceless Sneakers",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Laceless Sneakers: navy slip-on sneakers from Ndure (style M-PR-LEO-0028). They have a mesh and synthetic upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 5700,
    compareAtPriceCents: 8100,
    colors: [
      {
        slug: "navy",
        name: "Navy",
        swatch: ["#1d4e89"],
        images: ["ndure-leo-0028-navy-1","ndure-leo-0028-navy-2"],
        family: "blue",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Slip-On Sneakers","Mesh with Synthetic","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LEO-0028" },
      { label: "Upper Material", value: "Mesh with Synthetic" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Slip-On Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Slip-On Sneakers" },
    ],
    materials: "Mesh with Synthetic. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-luc-0027-khaki",
    slug: "ndure-luc-0027-khaki",
    name: "Men's Slip-On Shoes",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Slip-On Shoes: khaki casual slip-ons from Ndure (style M-PR-LUC-0027). They have a polyurethane upper on a man-made sole and thermoplastic sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 5100,
    compareAtPriceCents: 7200,
    colors: [
      {
        slug: "khaki",
        name: "Khaki",
        swatch: ["#b7a27a"],
        images: ["ndure-luc-0027-khaki-1","ndure-luc-0027-khaki-2"],
        family: "neutral",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Casual Slip-Ons","Polyurethane","Man-Made Sole/Thermoplastic"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-LUC-0027" },
      { label: "Upper Material", value: "Polyurethane" },
      { label: "Sole Material", value: "Man-Made Sole/Thermoplastic" },
      { label: "Silhouette", value: "Casual Slip-Ons" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Casual Slip-Ons" },
    ],
    materials: "Polyurethane. Man-Made Sole/Thermoplastic",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-trn-0014-black",
    slug: "ndure-trn-0014-black",
    name: "Men's Monochrome Slip-On Sneakers",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Monochrome Slip-On Sneakers: black slip-on sneakers from Ndure (style M-SN-TRN-0014). They have an engineered knit upper on a polyurethane (PU) sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 7600,
    compareAtPriceCents: 10800,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-trn-0014-black-1","ndure-trn-0014-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Slip-On Sneakers","Engineered Knit","Polyurethane"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SN-TRN-0014" },
      { label: "Upper Material", value: "Engineered Knit" },
      { label: "Sole Material", value: "Polyurethane" },
      { label: "Fashion Silhouette", value: "Slip-On Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Slip-On Sneakers" },
    ],
    materials: "Engineered Knit. Polyurethane",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-ori-0001-blk-wht",
    slug: "ndure-ori-0001-blk-wht",
    name: "Men's Chunky Sneakers",
    category: 'shoes',
    shoeUse: "lifestyle",
    variant: 'footwear',
    tagline: "Everyday sneaker",
    description: "Men's Chunky Sneakers: black and white lace-up sneakers from Ndure (style M-PR-ORI-0001). They have a polyurethane upper on an EVA foam sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 6900,
    compareAtPriceCents: 9900,
    colors: [
      {
        slug: "blk-wht",
        name: "Blk/Wht",
        swatch: ["#161616"],
        images: ["ndure-ori-0001-blk-wht-1","ndure-ori-0001-blk-wht-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Lace-up Sneakers","Polyurethane","Ethylene Vinyl Acetate"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-PR-ORI-0001" },
      { label: "Upper Material", value: "Polyurethane" },
      { label: "Sole Material", value: "Ethylene Vinyl Acetate" },
      { label: "Fashion Silhouette", value: "Lace-up Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Lace-up Sneakers" },
    ],
    materials: "Polyurethane. Ethylene Vinyl Acetate",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Lace-up, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
  {
    id: "ndure-luc-0010-black",
    slug: "ndure-luc-0010-black",
    name: "Men's Slip-On Sneakers in Black (LUC-0010)",
    category: 'shoes',
    shoeUse: "everyday",
    variant: 'footwear',
    tagline: "Slip-on sneaker",
    description: "Men's Slip-On Sneakers in Black (LUC-0010): slip-on sneakers from Ndure (style M-SC-LUC-0010). They have a polyurethane upper on a man-made sole and thermoplastic sole. Available in US men's sizes 7–12, standard width only. Best for everyday wear.",
    priceCents: 4400,
    compareAtPriceCents: 6300,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#161616"],
        images: ["ndure-luc-0010-black-1","ndure-luc-0010-black-2"],
        family: "black",
      },
    ],
    sizes: [7,8,9,10,11,12],
    widths: [STANDARD],
    highlights: ["Slip-On Sneakers","Polyurethane","Man-Made Sole/Thermoplastic"],
    specs: [
      { label: "Brand", value: "Ndure" },
      { label: "Style", value: "M-SC-LUC-0010" },
      { label: "Upper Material", value: "Polyurethane" },
      { label: "Sole Material", value: "Man-Made Sole/Thermoplastic" },
      { label: "Fashion Silhouette", value: "Slip-On Sneakers" },
    ],
    traits: [
      { group: 'Brand', value: 'Ndure' },
      { group: 'Style', value: "Slip-On Sneakers" },
    ],
    materials: "Polyurethane. Man-Made Sole/Thermoplastic",
    care: 'Wipe the upper with a damp cloth and mild soap. Air dry away from direct heat. Do not machine wash.',
    fit: {
      summary: "Slip-on, standard width.",
      advice: 'Order your usual US men’s size. This pair is not offered in a wide width.',
    },
    bestFor: ["Everyday wear"],
    defaultStock: 8,
    stock: {

    },
    relatedGuides: ['how-to-measure-your-feet'],
  },
]
