import type { Product, WidthOption } from './types.js'

const ONE: WidthOption = { code: 'OS', label: 'One size' }

/**
 * Men's wallets listed between 1,000 and 25,000 INR on Metro Shoes.
 * Each price is five times that listed price, converted at 95.88 INR per USD on 2026-09-27 and rounded to the nearest dollar.
 * The listed price is Metro's regular rupee price when it falls in that band. A lower promotional price is not used.
 */
export const mensWallets: Product[] = [
  {
    id: "metro-21-75-12-10",
    slug: "metro-21-75-12-10",
    name: "Metro Brown Wallet 21-75",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 11 × 2 × 9 cm",
    description: "Metro Brown Wallet 21-75 is a men's wallet in brown. Listed dimensions are 11 × 2 × 9 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-75-12-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6B4423"],
        images: ["metro-21-75-12-10-1","metro-21-75-12-10-2","metro-21-75-12-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Brown",
      "11 × 2 × 9 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Brown" },
      { label: "Dimensions", value: "11 × 2 × 9 cm" },
      { label: "SKU", value: "21-75-12-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Nation First International, 9, Vtm Bldg, Mehra Ind Compound, Saki Naka, Mumbai-400072, Maharashtra India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Brown" },
    ],
    materials: "Material is not published for this style. Colour: Brown.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-75-11-10",
    slug: "metro-21-75-11-10",
    name: "Metro Black Wallet 21-75",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 11 × 2 × 9 cm",
    description: "Metro Black Wallet 21-75 is a men's wallet in black. Listed dimensions are 11 × 2 × 9 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-75-11-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#1C1C1C"],
        images: ["metro-21-75-11-10-1","metro-21-75-11-10-2","metro-21-75-11-10-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Black",
      "11 × 2 × 9 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Black" },
      { label: "Dimensions", value: "11 × 2 × 9 cm" },
      { label: "SKU", value: "21-75-11-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Nation First International, 9, Vtm Bldg, Mehra Ind Compound, Saki Naka, Mumbai-400072, Maharashtra India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Black" },
    ],
    materials: "Material is not published for this style. Colour: Black.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-76-21-10",
    slug: "metro-21-76-21-10",
    name: "Metro Green Wallet 21-76",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 11 × 2 × 9 cm",
    description: "Metro Green Wallet 21-76 is a men's wallet in green. Listed dimensions are 11 × 2 × 9 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-76-21-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "green",
        name: "Green",
        swatch: ["#3E5C45"],
        images: ["metro-21-76-21-10-1","metro-21-76-21-10-2","metro-21-76-21-10-3"],
        family: "green",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Green",
      "11 × 2 × 9 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Green" },
      { label: "Dimensions", value: "11 × 2 × 9 cm" },
      { label: "SKU", value: "21-76-21-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Nation First International, 9, Vtm Bldg, Mehra Ind Compound, Saki Naka, Mumbai-400072, Maharashtra India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Green" },
    ],
    materials: "Material is not published for this style. Colour: Green.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-10-12-10",
    slug: "metro-21-10-12-10",
    name: "Metro Brown Wallet 21-10",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 24 × 2.5 × 8 cm",
    description: "Metro Brown Wallet 21-10 is a men's wallet in brown. Listed dimensions are 24 × 2.5 × 8 cm. The published material is Fabric. It is made to carry cards and folded cash. Country of origin: India. SKU 21-10-12-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6B4423"],
        images: ["metro-21-10-12-10-1","metro-21-10-12-10-2","metro-21-10-12-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Brown",
      "24 × 2.5 × 8 cm",
      "Fabric",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Brown" },
      { label: "Dimensions", value: "24 × 2.5 × 8 cm" },
      { label: "SKU", value: "21-10-12-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Arman Leather Works, Ground Floor, Shahstri Nagar, Dharavi Maim Road, Dharavi, Mumbai-400017, Maharashtra India" },
      { label: "Type", value: "Men's wallet" },
      { label: "Upper Material", value: "Fabric" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Brown" },
      { group: "Material", value: "Fabric" },
    ],
    materials: "Fabric.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-10-11-10",
    slug: "metro-21-10-11-10",
    name: "Metro Black Wallet 21-10",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 24 × 2.5 × 8 cm",
    description: "Metro Black Wallet 21-10 is a men's wallet in black. Listed dimensions are 24 × 2.5 × 8 cm. The published material is Fabric. It is made to carry cards and folded cash. Country of origin: India. SKU 21-10-11-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#1C1C1C"],
        images: ["metro-21-10-11-10-1","metro-21-10-11-10-2","metro-21-10-11-10-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Black",
      "24 × 2.5 × 8 cm",
      "Fabric",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Black" },
      { label: "Dimensions", value: "24 × 2.5 × 8 cm" },
      { label: "SKU", value: "21-10-11-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Arman Leather Works, Ground Floor, Shahstri Nagar, Dharavi Maim Road, Dharavi, Mumbai-400017, Maharashtra India" },
      { label: "Type", value: "Men's wallet" },
      { label: "Upper Material", value: "Fabric" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Black" },
      { group: "Material", value: "Fabric" },
    ],
    materials: "Fabric.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-7017-49-10",
    slug: "metro-21-7017-49-10",
    name: "Metro Olive Bifold 21-7017",
    category: 'wallets',
    variant: 'simple',
    tagline: "Bifold · 24 × 1.5 × 9 cm",
    description: "Metro Olive Bifold 21-7017 is a men's bifold in olive. Listed dimensions are 24 × 1.5 × 9 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-7017-49-10.",
    priceCents: 10400,
    colors: [
      {
        slug: "olive",
        name: "Olive",
        swatch: ["#6B7040"],
        images: ["metro-21-7017-49-10-1","metro-21-7017-49-10-2","metro-21-7017-49-10-3"],
        family: "green",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Bifold",
      "Olive",
      "24 × 1.5 × 9 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Bifold" },
      { label: "Colour", value: "Olive" },
      { label: "Dimensions", value: "24 × 1.5 × 9 cm" },
      { label: "SKU", value: "21-7017-49-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "M.N. Leather, 333/339, Shirin Manzil, 1St Floor Shop No. 11- Aar Street, Pinjara Lane, Mumbai-400008, Maharashtra India" },
      { label: "Type", value: "Bifold" },
    ],
    traits: [
      { group: "Style", value: "Bifold" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Olive" },
    ],
    materials: "Material is not published for this style. Colour: Olive.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-74-11-10",
    slug: "metro-21-74-11-10",
    name: "Metro Black Wallet 21-74",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 11 × 2 × 9 cm",
    description: "Metro Black Wallet 21-74 is a men's wallet in black. Listed dimensions are 11 × 2 × 9 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-74-11-10.",
    priceCents: 5700,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#1C1C1C"],
        images: ["metro-21-74-11-10-1","metro-21-74-11-10-2","metro-21-74-11-10-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Black",
      "11 × 2 × 9 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Black" },
      { label: "Dimensions", value: "11 × 2 × 9 cm" },
      { label: "SKU", value: "21-74-11-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Nation First International, 9, Vtm Bldg, Mehra Ind Compound, Saki Naka, Mumbai-400072, Maharashtra India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Black" },
    ],
    materials: "Material is not published for this style. Colour: Black.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-74-23-10",
    slug: "metro-21-74-23-10",
    name: "Metro Tan Wallet 21-74",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 11 × 2 × 9 cm",
    description: "Metro Tan Wallet 21-74 is a men's wallet in tan. Listed dimensions are 11 × 2 × 9 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-74-23-10.",
    priceCents: 5700,
    colors: [
      {
        slug: "tan",
        name: "Tan",
        swatch: ["#C4A574"],
        images: ["metro-21-74-23-10-1","metro-21-74-23-10-2","metro-21-74-23-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Tan",
      "11 × 2 × 9 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Tan" },
      { label: "Dimensions", value: "11 × 2 × 9 cm" },
      { label: "SKU", value: "21-74-23-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Nation First International, 9, Vtm Bldg, Mehra Ind Compound, Saki Naka, Mumbai-400072, Maharashtra India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Tan" },
    ],
    materials: "Material is not published for this style. Colour: Tan.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-7458-12-10",
    slug: "metro-21-7458-12-10",
    name: "Metro Brown Wallet 21-7458",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 11 × 2 × 9.5 cm",
    description: "Metro Brown Wallet 21-7458 is a men's wallet in brown. Listed dimensions are 11 × 2 × 9.5 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-7458-12-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6B4423"],
        images: ["metro-21-7458-12-10-1","metro-21-7458-12-10-2","metro-21-7458-12-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Brown",
      "11 × 2 × 9.5 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Brown" },
      { label: "Dimensions", value: "11 × 2 × 9.5 cm" },
      { label: "SKU", value: "21-7458-12-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Arman Leather Works, Ground Floor, Shahstri Nagar, Dharavi Maim Road, Dharavi, Mumbai-400017, Maharashtra India" },
      { label: "Type", value: "Men's wallet" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Brown" },
    ],
    materials: "Material is not published for this style. Colour: Brown.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-97-11-10",
    slug: "metro-21-97-11-10",
    name: "Metro Black Wallet 21-97",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Black Wallet 21-97 is a men's wallet in black. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-97-11-10.",
    priceCents: 8800,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#1C1C1C"],
        images: ["metro-21-97-11-10-1","metro-21-97-11-10-2","metro-21-97-11-10-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Black",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Black" },
      { label: "SKU", value: "21-97-11-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Euro International, Block-A 1St Floor, 4A, Gulam Jilani Khan Road, Topsia, Kolkata, West Bengal, Kolkata-700039, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Black" },
    ],
    materials: "Material is not published for this style. Colour: Black.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-62-23-10",
    slug: "metro-21-62-23-10",
    name: "Metro Tan Wallet 21-62",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 8.5 × 0.5 × 11 cm",
    description: "Metro Tan Wallet 21-62 is a men's wallet in tan. Listed dimensions are 8.5 × 0.5 × 11 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-62-23-10.",
    priceCents: 6700,
    colors: [
      {
        slug: "tan",
        name: "Tan",
        swatch: ["#C4A574"],
        images: ["metro-21-62-23-10-1","metro-21-62-23-10-2","metro-21-62-23-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Tan",
      "8.5 × 0.5 × 11 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Tan" },
      { label: "Dimensions", value: "8.5 × 0.5 × 11 cm" },
      { label: "SKU", value: "21-62-23-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Euro International, Block-A 1St Floor, 4A, Gulam Jilani Khan Road, Topsia, Kolkata, West Bengal, Kolkata-700039, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Tan" },
    ],
    materials: "Material is not published for this style. Colour: Tan.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-55-4-11-36",
    slug: "metro-55-4-11-36",
    name: "Metro Black Wallet 55-4",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Black Wallet 55-4 is a men's wallet in black. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 55-4-11-36.",
    priceCents: 13000,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#1C1C1C"],
        images: ["metro-55-4-11-36-1","metro-55-4-11-36-2","metro-55-4-11-36-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Black",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Black" },
      { label: "SKU", value: "55-4-11-36" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Chrometan Exports Pvt Ltd, 204 Ajc Bose Road 1St Floor, P-26 Kasba Industrial Estate Phae-2, Kolkata-700107, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Black" },
    ],
    materials: "Material is not published for this style. Colour: Black.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-55-4-12-36",
    slug: "metro-55-4-12-36",
    name: "Metro Brown Wallet 55-4",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Brown Wallet 55-4 is a men's wallet in brown. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 55-4-12-36.",
    priceCents: 13000,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6B4423"],
        images: ["metro-55-4-12-36-1","metro-55-4-12-36-2","metro-55-4-12-36-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Brown",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Brown" },
      { label: "SKU", value: "55-4-12-36" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Chrometan Exports Pvt Ltd, 204 Ajc Bose Road 1St Floor, P-26 Kasba Industrial Estate Phae-2, Kolkata-700107, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Brown" },
    ],
    materials: "Material is not published for this style. Colour: Brown.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-25-11-10",
    slug: "metro-21-25-11-10",
    name: "Metro Black Wallet 21-25",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Black Wallet 21-25 is a men's wallet in black. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-25-11-10.",
    priceCents: 6700,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#1C1C1C"],
        images: ["metro-21-25-11-10-1","metro-21-25-11-10-2","metro-21-25-11-10-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Black",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Black" },
      { label: "SKU", value: "21-25-11-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Arman Leather Works, 226 2/7.Ground Floor, Shahstri Nagar, Dharavi Maim Road, , Dharavi, Mumbai-400017, Maharashtra India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Black" },
    ],
    materials: "Material is not published for this style. Colour: Black.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-7017-23-10",
    slug: "metro-21-7017-23-10",
    name: "Metro Tan Bifold 21-7017",
    category: 'wallets',
    variant: 'simple',
    tagline: "Bifold · 24 × 1.5 × 9 cm",
    description: "Metro Tan Bifold 21-7017 is a men's bifold in tan. Listed dimensions are 24 × 1.5 × 9 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-7017-23-10.",
    priceCents: 10400,
    colors: [
      {
        slug: "tan",
        name: "Tan",
        swatch: ["#C4A574"],
        images: ["metro-21-7017-23-10-1","metro-21-7017-23-10-2","metro-21-7017-23-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Bifold",
      "Tan",
      "24 × 1.5 × 9 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Bifold" },
      { label: "Colour", value: "Tan" },
      { label: "Dimensions", value: "24 × 1.5 × 9 cm" },
      { label: "SKU", value: "21-7017-23-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Mens Wallets" },
      { label: "Manufacturer", value: "M.N. Leather, 333/339, Shirin Manzil, 1St Floor Shop No. 11- Aar Street, Pinjara Lane, Mumbai-400008, Maharashtra India" },
      { label: "Product", value: "Wallets" },
      { label: "Type", value: "Bifold" },
    ],
    traits: [
      { group: "Style", value: "Bifold" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Tan" },
    ],
    materials: "Material is not published for this style. Colour: Tan.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-7017-45-10",
    slug: "metro-21-7017-45-10",
    name: "Metro Blue Bifold 21-7017",
    category: 'wallets',
    variant: 'simple',
    tagline: "Bifold · 24 × 1.5 × 9 cm",
    description: "Metro Blue Bifold 21-7017 is a men's bifold in blue. Listed dimensions are 24 × 1.5 × 9 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-7017-45-10.",
    priceCents: 10400,
    colors: [
      {
        slug: "blue",
        name: "Blue",
        swatch: ["#1D4E89"],
        images: ["metro-21-7017-45-10-1","metro-21-7017-45-10-2","metro-21-7017-45-10-3"],
        family: "blue",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Bifold",
      "Blue",
      "24 × 1.5 × 9 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Bifold" },
      { label: "Colour", value: "Blue" },
      { label: "Dimensions", value: "24 × 1.5 × 9 cm" },
      { label: "SKU", value: "21-7017-45-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Mens Wallets" },
      { label: "Manufacturer", value: "M.N. Leather, 333/339, Shirin Manzil, 1St Floor Shop No. 11- Aar Street, Pinjara Lane, Mumbai-400008, Maharashtra India" },
      { label: "Product", value: "Wallets" },
      { label: "Type", value: "Bifold" },
    ],
    traits: [
      { group: "Style", value: "Bifold" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Blue" },
    ],
    materials: "Material is not published for this style. Colour: Blue.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-97-12-10",
    slug: "metro-21-97-12-10",
    name: "Metro Brown Wallet 21-97",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Brown Wallet 21-97 is a men's wallet in brown. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-97-12-10.",
    priceCents: 8800,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6B4423"],
        images: ["metro-21-97-12-10-1","metro-21-97-12-10-2","metro-21-97-12-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Brown",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Brown" },
      { label: "SKU", value: "21-97-12-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Euro International, Block-A 1St Floor, 4A, Gulam Jilani Khan Road, Topsia, Kolkata, West Bengal, Kolkata-700039, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Brown" },
    ],
    materials: "Material is not published for this style. Colour: Brown.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-101-12-10",
    slug: "metro-21-101-12-10",
    name: "Metro Brown Wallet 21-101",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Brown Wallet 21-101 is a men's wallet in brown. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-101-12-10.",
    priceCents: 8800,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6B4423"],
        images: ["metro-21-101-12-10-1","metro-21-101-12-10-2","metro-21-101-12-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Brown",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Brown" },
      { label: "SKU", value: "21-101-12-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Euro International, Block-A 1St Floor, 4A, Gulam Jilani Khan Road, Topsia, Kolkata, West Bengal, Kolkata-700039, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Brown" },
    ],
    materials: "Material is not published for this style. Colour: Brown.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-62-11-10",
    slug: "metro-21-62-11-10",
    name: "Metro Black Wallet 21-62",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 8.5 × 0.5 × 11 cm",
    description: "Metro Black Wallet 21-62 is a men's wallet in black. Listed dimensions are 8.5 × 0.5 × 11 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-62-11-10.",
    priceCents: 6700,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#1C1C1C"],
        images: ["metro-21-62-11-10-1","metro-21-62-11-10-2","metro-21-62-11-10-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Black",
      "8.5 × 0.5 × 11 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Black" },
      { label: "Dimensions", value: "8.5 × 0.5 × 11 cm" },
      { label: "SKU", value: "21-62-11-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Euro International, Block-A 1St Floor, 4A, Gulam Jilani Khan Road, Topsia, Kolkata, West Bengal, Kolkata-700039, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Black" },
    ],
    materials: "Material is not published for this style. Colour: Black.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-101-23-10",
    slug: "metro-21-101-23-10",
    name: "Metro Tan Wallet 21-101",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Tan Wallet 21-101 is a men's wallet in tan. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-101-23-10.",
    priceCents: 8800,
    colors: [
      {
        slug: "tan",
        name: "Tan",
        swatch: ["#C4A574"],
        images: ["metro-21-101-23-10-1","metro-21-101-23-10-2","metro-21-101-23-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Tan",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Tan" },
      { label: "SKU", value: "21-101-23-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Euro International, Block-A 1St Floor, 4A, Gulam Jilani Khan Road, Topsia, Kolkata, West Bengal, Kolkata-700039, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Tan" },
    ],
    materials: "Material is not published for this style. Colour: Tan.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-96-14-10",
    slug: "metro-21-96-14-10",
    name: "Metro Grey Wallet 21-96",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Grey Wallet 21-96 is a men's wallet in grey. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-96-14-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "grey",
        name: "Grey",
        swatch: ["#8A8A86"],
        images: ["metro-21-96-14-10-1","metro-21-96-14-10-2","metro-21-96-14-10-3"],
        family: "grey",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Grey",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Grey" },
      { label: "SKU", value: "21-96-14-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Euro International, Block-A 1St Floor, 4A, Gulam Jilani Khan Road, Topsia, Kolkata, West Bengal, Kolkata-700039, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Grey" },
    ],
    materials: "Material is not published for this style. Colour: Grey.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-96-22-10",
    slug: "metro-21-96-22-10",
    name: "Metro Rose Gold Wallet 21-96",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Rose Gold Wallet 21-96 is a men's wallet in rose gold. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-96-22-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "rose-gold",
        name: "Rose gold",
        swatch: ["#B76E79","#C6A15B"],
        images: ["metro-21-96-22-10-1","metro-21-96-22-10-2","metro-21-96-22-10-3"],
        family: "gold",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Rose gold",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Rose gold" },
      { label: "SKU", value: "21-96-22-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Euro International, Block-A 1St Floor, 4A, Gulam Jilani Khan Road, Topsia, Kolkata, West Bengal, Kolkata-700039, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Rose gold" },
    ],
    materials: "Material is not published for this style. Colour: Rose gold.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-40-12-10",
    slug: "metro-21-40-12-10",
    name: "Metro Brown Wallet 21-40",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 10 × 2 × 10 cm",
    description: "Metro Brown Wallet 21-40 is a men's wallet in brown. Listed dimensions are 10 × 2 × 10 cm. The published material is Synthetic. It is made to carry cards and folded cash. Country of origin: India. SKU 21-40-12-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6B4423"],
        images: ["metro-21-40-12-10-1","metro-21-40-12-10-2","metro-21-40-12-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Brown",
      "10 × 2 × 10 cm",
      "Synthetic",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Brown" },
      { label: "Dimensions", value: "10 × 2 × 10 cm" },
      { label: "SKU", value: "21-40-12-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Euro International, Block-A 1St Floor, 4A, Gulam Jilani Khan Road, Topsia, Kolkata, West Bengal, Kolkata-700039, West Bengal India" },
      { label: "Type", value: "Men's wallet" },
      { label: "Upper Material", value: "Synthetic" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Brown" },
      { group: "Material", value: "Synthetic" },
    ],
    materials: "Synthetic.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-99-11-10",
    slug: "metro-21-99-11-10",
    name: "Metro Black Wallet 21-99",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Black Wallet 21-99 is a men's wallet in black. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-99-11-10.",
    priceCents: 6700,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#1C1C1C"],
        images: ["metro-21-99-11-10-1","metro-21-99-11-10-2","metro-21-99-11-10-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Black",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Black" },
      { label: "SKU", value: "21-99-11-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Euro International, Block-A 1St Floor, 4A, Gulam Jilani Khan Road, Topsia, Kolkata, West Bengal, Kolkata-700039, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Black" },
    ],
    materials: "Material is not published for this style. Colour: Black.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-40-11-10",
    slug: "metro-21-40-11-10",
    name: "Metro Black Wallet 21-40",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 10 × 2 × 10 cm",
    description: "Metro Black Wallet 21-40 is a men's wallet in black. Listed dimensions are 10 × 2 × 10 cm. The published material is Synthetic. It is made to carry cards and folded cash. Country of origin: India. SKU 21-40-11-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#1C1C1C"],
        images: ["metro-21-40-11-10-1","metro-21-40-11-10-2","metro-21-40-11-10-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Black",
      "10 × 2 × 10 cm",
      "Synthetic",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Black" },
      { label: "Dimensions", value: "10 × 2 × 10 cm" },
      { label: "SKU", value: "21-40-11-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Euro International, Block-A 1St Floor, 4A, Gulam Jilani Khan Road, Topsia, Kolkata, West Bengal, Kolkata-700039, West Bengal India" },
      { label: "Type", value: "Men's wallet" },
      { label: "Upper Material", value: "Synthetic" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Black" },
      { group: "Material", value: "Synthetic" },
    ],
    materials: "Synthetic.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-99-12-10",
    slug: "metro-21-99-12-10",
    name: "Metro Brown Wallet 21-99",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Brown Wallet 21-99 is a men's wallet in brown. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-99-12-10.",
    priceCents: 6700,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6B4423"],
        images: ["metro-21-99-12-10-1","metro-21-99-12-10-2","metro-21-99-12-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Brown",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Brown" },
      { label: "SKU", value: "21-99-12-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Euro International, Block-A 1St Floor, 4A, Gulam Jilani Khan Road, Topsia, Kolkata, West Bengal, Kolkata-700039, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Brown" },
    ],
    materials: "Material is not published for this style. Colour: Brown.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-76-12-10",
    slug: "metro-21-76-12-10",
    name: "Metro Brown Wallet 21-76",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 11 × 2 × 9 cm",
    description: "Metro Brown Wallet 21-76 is a men's wallet in brown. Listed dimensions are 11 × 2 × 9 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-76-12-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6B4423"],
        images: ["metro-21-76-12-10-1","metro-21-76-12-10-2","metro-21-76-12-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Brown",
      "11 × 2 × 9 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Brown" },
      { label: "Dimensions", value: "11 × 2 × 9 cm" },
      { label: "SKU", value: "21-76-12-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Nation First International, 9, Vtm Bldg, Mehra Ind Compound, Saki Naka, Mumbai-400072, Maharashtra India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Brown" },
    ],
    materials: "Material is not published for this style. Colour: Brown.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-102-11-10",
    slug: "metro-21-102-11-10",
    name: "Metro Black Wallet 21-102",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Black Wallet 21-102 is a men's wallet in black. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-102-11-10.",
    priceCents: 6700,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#1C1C1C"],
        images: ["metro-21-102-11-10-1","metro-21-102-11-10-2","metro-21-102-11-10-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Black",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Black" },
      { label: "SKU", value: "21-102-11-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Chrometan Exports Pvt Ltd, 204 Ajc Bose Road 1St Floor, P-26 Kasba Industrial Estate Phae-2, Kolkata-700107, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Black" },
    ],
    materials: "Material is not published for this style. Colour: Black.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-26-11-10",
    slug: "metro-21-26-11-10",
    name: "Metro Black Wallet 21-26",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 22.8 × 1.8 × 8 cm",
    description: "Metro Black Wallet 21-26 is a men's wallet in black. Listed dimensions are 22.8 × 1.8 × 8 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-26-11-10.",
    priceCents: 8800,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#1C1C1C"],
        images: ["metro-21-26-11-10-1","metro-21-26-11-10-2","metro-21-26-11-10-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Black",
      "22.8 × 1.8 × 8 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Black" },
      { label: "Dimensions", value: "22.8 × 1.8 × 8 cm" },
      { label: "SKU", value: "21-26-11-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Arman Leather Works, Ground Floor, Shahstri Nagar, Dharavi Maim Road, Dharavi, Mumbai-400017, Maharashtra India" },
      { label: "Type", value: "Men's wallet" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Black" },
    ],
    materials: "Material is not published for this style. Colour: Black.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-102-22-10",
    slug: "metro-21-102-22-10",
    name: "Metro Rose Gold Wallet 21-102",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Rose Gold Wallet 21-102 is a men's wallet in rose gold. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-102-22-10.",
    priceCents: 6700,
    colors: [
      {
        slug: "rose-gold",
        name: "Rose gold",
        swatch: ["#B76E79","#C6A15B"],
        images: ["metro-21-102-22-10-1","metro-21-102-22-10-2","metro-21-102-22-10-3"],
        family: "gold",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Rose gold",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Rose gold" },
      { label: "SKU", value: "21-102-22-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Chrometan Exports Pvt Ltd, 204 Ajc Bose Road 1St Floor, P-26 Kasba Industrial Estate Phae-2, Kolkata-700107, West Bengal India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Rose gold" },
    ],
    materials: "Material is not published for this style. Colour: Rose gold.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-26-23-10",
    slug: "metro-21-26-23-10",
    name: "Metro Tan Wallet 21-26",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet · 22.8 × 1.8 × 8 cm",
    description: "Metro Tan Wallet 21-26 is a men's wallet in tan. Listed dimensions are 22.8 × 1.8 × 8 cm. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-26-23-10.",
    priceCents: 8800,
    colors: [
      {
        slug: "tan",
        name: "Tan",
        swatch: ["#C4A574"],
        images: ["metro-21-26-23-10-1","metro-21-26-23-10-2","metro-21-26-23-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Tan",
      "22.8 × 1.8 × 8 cm",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Tan" },
      { label: "Dimensions", value: "22.8 × 1.8 × 8 cm" },
      { label: "SKU", value: "21-26-23-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "Arman Leather Works, Ground Floor, Shahstri Nagar, Dharavi Maim Road, Dharavi, Mumbai-400017, Maharashtra India" },
      { label: "Type", value: "Men's wallet" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Tan" },
    ],
    materials: "Material is not published for this style. Colour: Tan.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-6904-23-10",
    slug: "metro-21-6904-23-10",
    name: "Metro Tan Bifold 21-6904",
    category: 'wallets',
    variant: 'simple',
    tagline: "Bifold",
    description: "Metro Tan Bifold 21-6904 is a men's bifold in tan. The published material is Leather. It is made to carry cards and folded cash. Country of origin: India. SKU 21-6904-23-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "tan",
        name: "Tan",
        swatch: ["#C4A574"],
        images: ["metro-21-6904-23-10-1","metro-21-6904-23-10-2","metro-21-6904-23-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Bifold",
      "Tan",
      "Leather",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Bifold" },
      { label: "Colour", value: "Tan" },
      { label: "SKU", value: "21-6904-23-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Mens Wallets" },
      { label: "Manufacturer", value: "M.N. Leather, 333/339, Shirin Manzil, 1St Floor Shop No. 11- Aar Street, Pinjara Lane, Mumbai-400008, Maharashtra India" },
      { label: "Product", value: "Wallets" },
      { label: "Type", value: "Bifold" },
      { label: "Upper Material", value: "Leather" },
    ],
    traits: [
      { group: "Style", value: "Bifold" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Tan" },
      { group: "Material", value: "Leather" },
    ],
    materials: "Leather.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-6904-49-10",
    slug: "metro-21-6904-49-10",
    name: "Metro Olive Wallet 21-6904",
    category: 'wallets',
    variant: 'simple',
    tagline: "Wallet",
    description: "Metro Olive Wallet 21-6904 is a men's wallet in olive. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-6904-49-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "olive",
        name: "Olive",
        swatch: ["#6B7040"],
        images: ["metro-21-6904-49-10-1","metro-21-6904-49-10-2","metro-21-6904-49-10-3"],
        family: "green",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Wallet",
      "Olive",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Wallet" },
      { label: "Colour", value: "Olive" },
      { label: "SKU", value: "21-6904-49-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Men's wallet" },
      { label: "Manufacturer", value: "M.N. Leather, 333/339, Shirin Manzil, 1St Floor Shop No. 11- Aar Street, Pinjara Lane, Mumbai-400008, Maharashtra India" },
    ],
    traits: [
      { group: "Style", value: "Wallet" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Olive" },
    ],
    materials: "Material is not published for this style. Colour: Olive.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-6904-12-10",
    slug: "metro-21-6904-12-10",
    name: "Metro Brown Bifold 21-6904",
    category: 'wallets',
    variant: 'simple',
    tagline: "Bifold",
    description: "Metro Brown Bifold 21-6904 is a men's bifold in brown. The published material is Leather. It is made to carry cards and folded cash. Country of origin: INDIA. SKU 21-6904-12-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "brown",
        name: "Brown",
        swatch: ["#6B4423"],
        images: ["metro-21-6904-12-10-1","metro-21-6904-12-10-2","metro-21-6904-12-10-3"],
        family: "neutral",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Bifold",
      "Brown",
      "Leather",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Bifold" },
      { label: "Colour", value: "Brown" },
      { label: "SKU", value: "21-6904-12-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "INDIA" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Mens Wallets" },
      { label: "Manufacturer", value: "M.N. Leather, Green Chamber, Shop No.1, A, Sofia Zubair Road, Nagpada, Mumbai-400008-India" },
      { label: "Product", value: "Wallets" },
      { label: "Type", value: "Bifold" },
      { label: "Upper Material", value: "Leather" },
    ],
    traits: [
      { group: "Style", value: "Bifold" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Brown" },
      { group: "Material", value: "Leather" },
    ],
    materials: "Leather.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-6904-11-10",
    slug: "metro-21-6904-11-10",
    name: "Metro Black Bifold 21-6904",
    category: 'wallets',
    variant: 'simple',
    tagline: "Bifold",
    description: "Metro Black Bifold 21-6904 is a men's bifold in black. The published material is Leather. It is made to carry cards and folded cash. Country of origin: India. SKU 21-6904-11-10.",
    priceCents: 7800,
    colors: [
      {
        slug: "black",
        name: "Black",
        swatch: ["#1C1C1C"],
        images: ["metro-21-6904-11-10-1","metro-21-6904-11-10-2","metro-21-6904-11-10-3"],
        family: "black",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Bifold",
      "Black",
      "Leather",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Bifold" },
      { label: "Colour", value: "Black" },
      { label: "SKU", value: "21-6904-11-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Mens Wallets" },
      { label: "Manufacturer", value: "M.N. Leather, 333/339, Shirin Manzil, 1St Floor Shop No. 11- Aar Street, Pinjara Lane, Mumbai-400008, Maharashtra India" },
      { label: "Product", value: "Wallets" },
      { label: "Type", value: "Bifold" },
      { label: "Upper Material", value: "Leather" },
    ],
    traits: [
      { group: "Style", value: "Bifold" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Black" },
      { group: "Material", value: "Leather" },
    ],
    materials: "Leather.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-8250-44-10",
    slug: "metro-21-8250-44-10",
    name: "Metro Maroon Money Clip 21-8250",
    category: 'wallets',
    variant: 'simple',
    tagline: "Money clip",
    description: "Metro Maroon Money Clip 21-8250 is a men's money clip in maroon. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-8250-44-10.",
    priceCents: 6700,
    colors: [
      {
        slug: "maroon",
        name: "Maroon",
        swatch: ["#6B1F26"],
        images: ["metro-21-8250-44-10-1","metro-21-8250-44-10-2","metro-21-8250-44-10-3"],
        family: "red",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Money clip",
      "Maroon",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Money clip" },
      { label: "Colour", value: "Maroon" },
      { label: "SKU", value: "21-8250-44-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Mens Wallets" },
      { label: "Manufacturer", value: "Arman Leather Works, Ground Floor, Shahstri Nagar, Dharavi Maim Road, Dharavi, Mumbai-400017, Maharashtra India" },
      { label: "Product", value: "Wallets" },
      { label: "Type", value: "Money Clip Wallet" },
    ],
    traits: [
      { group: "Style", value: "Money clip" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Maroon" },
    ],
    materials: "Material is not published for this style. Colour: Maroon.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
  {
    id: "metro-21-8250-45-10",
    slug: "metro-21-8250-45-10",
    name: "Metro Blue Money Clip 21-8250",
    category: 'wallets',
    variant: 'simple',
    tagline: "Money clip",
    description: "Metro Blue Money Clip 21-8250 is a men's money clip in blue. Metro does not publish a material for this style. It is made to carry cards and folded cash. Country of origin: India. SKU 21-8250-45-10.",
    priceCents: 6700,
    colors: [
      {
        slug: "blue",
        name: "Blue",
        swatch: ["#1D4E89"],
        images: ["metro-21-8250-45-10-1","metro-21-8250-45-10-2","metro-21-8250-45-10-3"],
        family: "blue",
      },
    ],
    sizes: [0],
    widths: [ONE],
    highlights: [
      "Money clip",
      "Blue",
    ],
    specs: [
      { label: "Brand", value: "Metro" },
      { label: "Style", value: "Money clip" },
      { label: "Colour", value: "Blue" },
      { label: "SKU", value: "21-8250-45-10" },
      { label: "Size", value: "One Size" },
      { label: "Country of Origin", value: "India" },
      { label: "Net quantity", value: "1" },
      { label: "Occasion", value: "Mens Wallets" },
      { label: "Manufacturer", value: "Arman Leather Works, Ground Floor, Shahstri Nagar, Dharavi Maim Road, Dharavi, Mumbai-400017, Maharashtra India" },
      { label: "Product", value: "Wallets" },
      { label: "Type", value: "Money Clip Wallet" },
    ],
    traits: [
      { group: "Style", value: "Money clip" },
      { group: "Brand", value: "Metro" },
      { group: "Color", value: "Blue" },
    ],
    materials: "Material is not published for this style. Colour: Blue.",
    care: 'Wipe with a soft dry cloth. Keep the wallet away from prolonged rain and do not machine wash it.',
    fit: {
      summary: 'One size.',
      advice: 'Built for cards and folded cash. Use the dimensions in the specifications to check pocket fit.',
    },
    bestFor: ["Everyday carry"],
    defaultStock: 8,
    stock: {},
    relatedGuides: ['what-fits-in-a-crossbody-bag'],
  },
]
